// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-17, for A-MoreTesting, from my decision that the
// four task classes were only ever checked in passing, inside assertions
// belonging to the storage and list tests, and deserve tests of their own.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.task;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

/**
 * Tests the four task classes: what a task shows the user, and what it writes
 * to the save file.
 * <p>
 * These two forms are separate on purpose, and the tests keep them separate.
 * {@code toString} is for a person to read and may be reworded at any time.
 * {@code toSaveFormat} is data that {@link gudgoi.Storage} has to read back,
 * so a change there breaks every file a user already has.
 * <p>
 * Both forms were previously checked only in passing, inside assertions that
 * belonged to the storage and list tests. A fault in either would have
 * surfaced there as a confusing failure about saving rather than as a plain
 * statement that a task prints wrongly.
 */
public class TaskTest {

    /** 15 October 2019, 09:00, the moment the other tests already use. */
    private static final LocalDateTime NINE_AM = LocalDateTime.of(2019, 10, 15, 9, 0);

    /** 15 October 2019, 18:30, so a second time cannot be confused with the first. */
    private static final LocalDateTime HALF_SIX = LocalDateTime.of(2019, 10, 15, 18, 30);

    // ---------- the status box ----------

    @Test
    public void isMarked_aNewTask_isNotDone() {
        assertFalse(new Todo("read book").isMarked());
    }

    @Test
    public void isMarked_afterMark_isDone() {
        Todo todo = new Todo("read book");
        todo.mark();
        assertTrue(todo.isMarked());
    }

    @Test
    public void isMarked_afterMarkThenUnmark_isNotDoneAgain() {
        Todo todo = new Todo("read book");
        todo.mark();
        todo.unmark();
        assertFalse(todo.isMarked());
    }

    @Test
    public void mark_aTaskAlreadyDone_leavesItDone() {
        Todo todo = new Todo("read book");
        todo.mark();
        todo.mark();
        assertTrue(todo.isMarked());
    }

    @Test
    public void unmark_aTaskThatWasNeverDone_leavesItNotDone() {
        Todo todo = new Todo("read book");
        todo.unmark();
        assertFalse(todo.isMarked());
    }

    // ---------- what the user reads ----------

    @Test
    public void toString_newTodo_showsTheTypeAndAnEmptyBox() {
        assertEquals("[T][ ] read book", new Todo("read book").toString());
    }

    @Test
    public void toString_todoThatIsDone_showsTheCross() {
        Todo todo = new Todo("read book");
        todo.mark();
        assertEquals("[T][X] read book", todo.toString());
    }

    @Test
    public void toString_deadline_appendsTheByPart() {
        assertEquals("[D][ ] submit report (by: Oct 15 2019, 09:00)",
                new Deadline("submit report", NINE_AM).toString());
    }

    @Test
    public void toString_event_appendsBothTimes() {
        assertEquals("[E][ ] team meeting (from: Oct 15 2019, 09:00 to: Oct 15 2019, 18:30)",
                new Event("team meeting", NINE_AM, HALF_SIX).toString());
    }

    @Test
    public void toString_deadlineThatIsDone_keepsTheByPart() {
        Deadline deadline = new Deadline("submit report", NINE_AM);
        deadline.mark();
        assertEquals("[D][X] submit report (by: Oct 15 2019, 09:00)", deadline.toString());
    }

    @Test
    public void toString_separatorInTheDescription_isShownAsTyped() {
        // The escaping belongs to the save form. What the user typed is what
        // the user should read back.
        assertEquals("[T][ ] pay rent | utilities",
                new Todo("pay rent | utilities").toString());
    }

    // ---------- what the file holds ----------

    @Test
    public void toSaveFormat_newTodo_writesZeroForNotDone() {
        assertEquals("T | 0 | read book", new Todo("read book").toSaveFormat());
    }

    @Test
    public void toSaveFormat_todoThatIsDone_writesOne() {
        Todo todo = new Todo("read book");
        todo.mark();
        assertEquals("T | 1 | read book", todo.toSaveFormat());
    }

    @Test
    public void toSaveFormat_deadline_writesTheTimeAsIso() {
        assertEquals("D | 0 | submit report | 2019-10-15T09:00",
                new Deadline("submit report", NINE_AM).toSaveFormat());
    }

    @Test
    public void toSaveFormat_event_writesBothTimes() {
        assertEquals("E | 0 | team meeting | 2019-10-15T09:00 | 2019-10-15T18:30",
                new Event("team meeting", NINE_AM, HALF_SIX).toSaveFormat());
    }

    @Test
    public void toSaveFormat_separatorInTheDescription_isEscaped() {
        // An unescaped bar would look like a field separator when the line is
        // read back and would shift every field after it.
        assertEquals("T | 0 | pay rent \\| utilities",
                new Todo("pay rent | utilities").toSaveFormat());
    }

    @Test
    public void toSaveFormat_separatorInADeadlineDescription_doesNotShiftTheTime() {
        assertEquals("D | 0 | a \\| b | 2019-10-15T09:00",
                new Deadline("a | b", NINE_AM).toSaveFormat());
    }

    // ---------- the description is kept exactly ----------

    @Test
    public void getDescription_anyTask_returnsWhatItWasBuiltWith() {
        assertEquals("read book", new Todo("read book").getDescription());
    }

    @Test
    public void getBy_aDeadline_returnsTheMomentItWasBuiltWith() {
        assertEquals(NINE_AM, new Deadline("submit report", NINE_AM).getBy());
    }

    @Test
    public void getFromAndGetTo_anEvent_returnBothMoments() {
        Event event = new Event("team meeting", NINE_AM, HALF_SIX);
        assertEquals(NINE_AM, event.getFrom());
        assertEquals(HALF_SIX, event.getTo());
    }
}
