// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: use inheritance to
// create the Level-4 task subclasses. The getTypeLetter and toSaveFormat
// methods were generated the same way on 2026-08-27, for the Level-7 save
// format. The change from String times to LocalDateTime was generated the same
// way on 2026-08-27, for Level-8. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.task;

import java.time.LocalDateTime;

/**
 * A task that runs between two times, for example
 * {@code project meeting /from 2019-10-15 1400 /to 2019-10-15 1600}.
 * <p>
 * Shown to the user as
 * {@code [E][ ] project meeting (from: Oct 15 2019, 14:00 to: Oct 15 2019, 16:00)}.
 */
public class Event extends Task {
    /**
     * When the event starts, as a point in time rather than as text.
     * A user who gives only a date gets midnight at the start of that day.
     */
    private final LocalDateTime from;

    /**
     * When the event ends, as a point in time rather than as text.
     * A user who gives only a date gets the last minute of that day, so that a
     * whole-day event covers the whole day.
     */
    private final LocalDateTime to;

    /**
     * Creates an event that is not done yet.
     *
     * @param description text the user entered
     * @param from when the event starts
     * @param to when the event ends
     */
    public Event(String description, LocalDateTime from, LocalDateTime to) {
        super(description);
        this.from = from;
        this.to = to;
    }

    /**
     * Returns when this event starts.
     *
     * @return the start time
     */
    public LocalDateTime getFrom() {
        return this.from;
    }

    /**
     * Returns when this event ends.
     *
     * @return the end time
     */
    public LocalDateTime getTo() {
        return this.to;
    }

    /** {@inheritDoc} An event shows {@code [E]}. */
    @Override
    protected String getTypeIcon() {
        return "[E]";
    }

    /** {@inheritDoc} An event is stored as {@code E}. */
    @Override
    protected String getTypeLetter() {
        return "E";
    }

    /**
     * {@inheritDoc}
     * An event appends two fields, its start and its end, both in the
     * ISO form that {@link gudgoi.Storage} reads back.
     */
    @Override
    public String toSaveFormat() {
        // The ISO form of a LocalDateTime holds no | of its own, so neither
        // field needs escaping.
        return super.toSaveFormat() + " | " + this.from + " | " + this.to;
    }

    /**
     * {@inheritDoc}
     * An event appends {@code (from: ... to: ...)}, with both times
     * written the way a person reads them.
     */
    @Override
    public String toString() {
        return super.toString() + " (from: " + this.from.format(DISPLAY_FORMAT)
                + " to: " + this.to.format(DISPLAY_FORMAT) + ")";
    }
}
