// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: a Task class in its
// own file with a boolean `marked` field. The getTypeIcon hook and the
// matching change to toString, added for the Level-4 subclasses, were
// generated the same way and on the same day. The getTypeLetter, toSaveFormat
// and escape methods were generated the same way on 2026-08-27, for the
// Level-7 save format. The DISPLAY_FORMAT field was generated the same way on
// 2026-08-27, for the Level-8 date handling. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.task;

import java.time.format.DateTimeFormatter;

/**
 * One item on the user's agenda.
 * <p>
 * A task holds the text the user typed and whether it has been completed.
 * Tasks start off not done.
 */
public class Task {
    /**
     * How a date and time is shown to the user, for example
     * {@code Oct 15 2019, 18:00}.
     * <p>
     * It sits here because both subclasses that carry times need it, and
     * because deciding how a task looks is this class's job. It is deliberately
     * not the format the user types, nor the format the save file holds.
     * <p>
     * It is public because a message about a task may have to show a time the
     * same way, and the class that writes such a message is not a task. A
     * {@link DateTimeFormatter} cannot be changed once built, so sharing this
     * one hands out no control over it.
     */
    public static final DateTimeFormatter DISPLAY_FORMAT =
            DateTimeFormatter.ofPattern("MMM dd yyyy, HH:mm");

    /** Text the user entered to describe this task. */
    private final String description;

    /** Whether the user has marked this task as done. */
    private boolean marked;

    /**
     * Creates a task that is not done yet.
     *
     * @param description text the user entered
     */
    public Task(String description) {
        this.description = description;
        this.marked = false;
    }

    /** Marks this task as done. */
    public void mark() {
        this.marked = true;
    }

    /** Marks this task as not done. */
    public void unmark() {
        this.marked = false;
    }

    /**
     * Returns whether this task is done.
     *
     * @return true if the task has been marked as done
     */
    public boolean isMarked() {
        return this.marked;
    }

    /**
     * Returns the text the user entered for this task.
     *
     * @return the task description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Returns the letter box shown before the status box, for example
     * {@code [T]}. A plain task has no letter; each subclass supplies its own.
     *
     * @return the type marker for this kind of task
     */
    protected String getTypeIcon() {
        return "";
    }

    /**
     * Returns the single letter that identifies this kind of task in the save
     * file, for example {@code T}. A plain task has no letter; each subclass
     * supplies its own.
     *
     * @return the type letter for this kind of task
     */
    protected String getTypeLetter() {
        return "";
    }

    /**
     * Returns the task as one line of the save file, for example
     * {@code T | 1 | read book}. Fields are separated by {@code " | "}, and a
     * done task carries {@code 1} while a task still to do carries {@code 0}.
     * Subclasses append the extra fields they hold.
     * <p>
     * This is deliberately separate from {@link #toString()}. The display form
     * exists for the user to read and is free to change; the save form is data
     * that {@link gudgoi.Storage} has to read back.
     *
     * @return the storage form of this task
     */
    public String toSaveFormat() {
        return this.getTypeLetter() + " | " + (this.marked ? "1" : "0")
                + " | " + escape(this.description);
    }

    /**
     * Returns text that is safe to write as one field of a save-file line.
     * <p>
     * A {@code |} inside the text would look like a field separator when the
     * line is read back, which would shift every field after it. Writing it as
     * {@code \|} keeps the field count right. {@link gudgoi.Storage}
     * reverses this when it reads the line.
     *
     * @param text the raw text of one field
     * @return the text with every {@code |} written as {@code \|}
     */
    protected static String escape(String text) {
        return text.replace("|", "\\|");
    }

    /**
     * Returns the task as it is shown to the user: the type box, the status
     * box, then the description, for example {@code [T][X] read book}.
     * <p>
     * Subclasses that carry extra details override this and append to
     * {@code super.toString()}, so the common part stays in one place.
     *
     * @return the display form of this task
     */
    @Override
    public String toString() {
        return this.getTypeIcon() + (this.marked ? "[X] " : "[ ] ") + this.description;
    }
}
