// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: use inheritance to
// create the Level-4 task subclasses. The getTypeLetter method was generated the same
// way on 2026-08-27, for the Level-7 save format. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.task;

/**
 * A task with no date attached, for example {@code visit new theme park}.
 * <p>
 * Shown to the user as {@code [T][ ] visit new theme park}.
 */
public class Todo extends Task {
    /**
     * Creates a todo that is not done yet.
     *
     * @param description text the user entered
     */
    public Todo(String description) {
        super(description);
    }

    @Override
    protected String getTypeIcon() {
        return "[T]";
    }

    @Override
    protected String getTypeLetter() {
        return "T";
    }
}
