package gudgoi;

import java.nio.file.Path;
import java.util.List;

import gudgoi.exception.CommandNotFoundException;
import gudgoi.exception.GudGoiException;
import gudgoi.exception.TaskLoadException;
import gudgoi.exception.TaskSaveException;
import gudgoi.task.Task;

/**
 * The chatbot itself: one bot, holding the four parts and deciding the order
 * they work in.
 * <p>
 * {@link Ui} speaks and listens, {@link Storage} keeps the file,
 * {@link TaskList} holds the tasks, and {@link Parser} reads what the user
 * typed. None of them knows about the others. What is left here is the order:
 * change the list, write it, undo the change if the write failed, then say what
 * happened.
 */
public class GudGoi {
    // ---------------------------------------------------------------------
    // AI-ASSISTED CODE — CITATION
    // Much of this class was generated by Claude (Anthropic), used through
    // Claude Code, on 2026-08-20 and 2026-08-21, from the Level-2 to Level-5
    // requirements: tasks, listTasks, mark, unmark, addAndConfirm and the
    // command dispatch in main. The printing, the storage, the list itself and
    // the command reading were generated the same way and have since moved to
    // Ui, Storage, TaskList and Parser. I reviewed the code before committing
    // it, and rewrote parts of it myself.
    // ---------------------------------------------------------------------

    /** The one way in and out for anything the user sees or types. */
    private final Ui ui;

    /** The agenda on disk. */
    private final Storage storage;

    /**
     * The agenda in memory.
     * <p>
     * It is replaced, not filled, once storage has been asked for its
     * contents, so it cannot be {@code final}.
     */
    private TaskList tasks;

    /**
     * Builds a bot that keeps its agenda in one file.
     * <p>
     * It wires the parts together and nothing else. Reading the file is left
     * to {@link #run()}, so that the user is greeted before being told
     * anything about a file, and so that building a bot cannot fail.
     *
     * @param savePath where the agenda is kept, relative to the folder the
     *                 program runs in
     */
    public GudGoi(Path savePath) {
        this.ui = new Ui();
        this.storage = new Storage(savePath);
        this.tasks = new TaskList();
    }

    /**
     * Stores a task and prints the confirmation shared by all three add
     * commands, including the running total.
     *
     * @param task the task that was just built
     * @throws TaskSaveException if the new list cannot be written, in which
     *                           case the task is taken out again
     */
    private void addAndConfirm(Task task) throws TaskSaveException {
        tasks.add(task);
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            tasks.removeLast();
            throw e;
        }
        ui.show("Got it. I've added this task:\n  " + task
                + "\nNow you have " + tasks.size()
                + (tasks.size() == 1 ? " task" : " tasks") + " in the list.");
    }

    /** Prints every stored task, numbered from 1. */
    private void listTasks() {
        if (tasks.isEmpty()) {
            ui.show("Nothing on the agenda yet.");
            return;
        }

        List<Task> all = tasks.asList();
        StringBuilder list = new StringBuilder();
        for (int i = 0; i < all.size(); i++) {
            // Tasks are numbered from 1 for the user, but indexed from 0 here.
            // Task.toString() supplies the "[X] " or "[ ] " status box.
            list.append(i + 1).append(".").append(all.get(i));
            if (i < all.size() - 1) {
                list.append("\n");
            }
        }
        ui.show(list.toString());
    }

    /**
     * Marks the task the user named as done, then confirms it.
     *
     * @param number the text the user gave after {@code mark}
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         change that cannot be saved is undone first, so
     *                         the list still matches the file.
     */
    private void mark(String number)
            throws GudGoiException {
        Task task = tasks.get(Parser.parsePosition(number));
        // The task may already be done, so the undo restores what was there
        // before rather than assuming it was not done.
        boolean wasMarked = task.isMarked();
        task.mark();
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            if (!wasMarked) {
                task.unmark();
            }
            throw e;
        }
        ui.show("Nice! I've marked this task as done:\n  " + task);
    }

    /**
     * Marks the task the user named as not done, then confirms it.
     *
     * @param number the text the user gave after {@code unmark}
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         change that cannot be saved is undone first, so
     *                         the list still matches the file.
     */
    private void unmark(String number)
            throws GudGoiException {
        Task task = tasks.get(Parser.parsePosition(number));
        boolean wasMarked = task.isMarked();
        task.unmark();
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            if (wasMarked) {
                task.mark();
            }
            throw e;
        }
        ui.show("OK, I've marked this task as not done yet:\n  " + task);
    }

    /**
     * Deletes the task the user named.
     *
     * @param number the text the user gave after {@code delete}
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         deletion that cannot be saved is undone, and the
     *                         task goes back where it was.
     */
    private void deleteTask(String number)
            throws GudGoiException {
        int position = Parser.parsePosition(number);
        Task task = tasks.remove(position);
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            tasks.insert(position, task);
            throw e;
        }
        ui.show("Noted. I've removed this task:\n  " + task
                + "\nNow you have " + tasks.size() + " task(s) in the list.");
    }

    /**
     * Carries out one line of input from the user.
     * <p>
     * The loop in {@link #run()} reads lines; this method decides what a line
     * means and does it. Anything the user got wrong leaves here as a
     * {@link GudGoiException} for the caller to report.
     *
     * @param line one line the user typed, already trimmed
     * @throws GudGoiException if the command or its arguments are unusable
     */
    private void handle(String line) throws GudGoiException {
        String command = Parser.commandWord(line);
        String rest = Parser.arguments(line);

        // Building the task is the Parser's answer to the command; storing it
        // and saying so is this class's.
        switch (command) {
        case "list" -> listTasks();
        case "mark" -> mark(rest);
        case "unmark" -> unmark(rest);
        case "todo" -> addAndConfirm(Parser.parseTodo(rest));
        case "deadline" -> addAndConfirm(Parser.parseDeadline(rest));
        case "event" -> addAndConfirm(Parser.parseEvent(rest));
        case "delete" -> deleteTask(rest);
        default -> throw new CommandNotFoundException();
        }
    }

    /**
     * Runs one session: greets the user, restores the saved agenda, then reads
     * and carries out commands until {@code bye} or the end of input.
     * <p>
     * The agenda is read here rather than in the constructor, so that the
     * greeting comes first. A user who is told their save file was deleted
     * before the bot has said hello has no idea who is talking.
     */
    public void run() {
        ui.showBanner();
        ui.showGreeting();

        try {
            tasks = new TaskList(storage.load());
        } catch (TaskLoadException e) {
            // A missing or damaged file costs the old agenda, not the session.
            ui.showError(e.getMessage());
        }

        String line;
        while (!(line = ui.readCommand()).equals("bye")) {
            try {
                handle(line);
            } catch (GudGoiException e) {
                ui.showError(e.getMessage());
            }
        }

        ui.showFarewell();
    }

    /**
     * Starts the bot.
     * <p>
     * {@link Path#of} joins the parts with the separator the host system uses,
     * so this one line works on Windows and on Linux without a change.
     *
     * @param args ignored; the bot takes no command line arguments
     */
    public static void main(String[] args) {
        new GudGoi(Path.of("data", "saved.txt")).run();
    }
}
