package gudgoi;

import java.nio.file.Path;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import gudgoi.exception.CardSaveException;
import gudgoi.exception.CommandNotFoundException;
import gudgoi.exception.GudGoiException;
import gudgoi.exception.TaskLoadException;
import gudgoi.exception.TaskSaveException;
import gudgoi.task.Task;
import gudgoi.trivia.Card;
import gudgoi.trivia.CardList;
import gudgoi.trivia.CardStorage;

/**
 * The chatbot itself: one bot, holding the four parts and deciding the order
 * they work in.
 * <p>
 * {@link Ui} speaks and listens, {@link Storage} keeps the file,
 * {@link TaskList} holds the tasks, and {@link Parser} reads what the user
 * typed. None of them knows about the others. What is left here is the order:
 * change the list, write it, undo the change if the write failed, then say what
 * happened.
 */
public class GudGoi {
    // ---------------------------------------------------------------------
    // AI-ASSISTED CODE — CITATION
    // Much of this class was generated by Claude (Anthropic), used through
    // Claude Code, on 2026-08-20 and 2026-08-21, from the Level-2 to Level-5
    // requirements: tasks, listTasks, mark, unmark, addAndConfirm and the
    // command dispatch in main. The printing, the storage, the list itself and
    // the command reading were generated the same way and have since moved to
    // Ui, Storage, TaskList and Parser. I reviewed the code before committing
    // it, and rewrote parts of it myself.
    // The command loop in run was rewritten the same way on 2026-09-03, after a
    // peer review asked for the assignment to come out of the while condition.
    // The change from printing to returning text, and getGreeting, loadTasks,
    // getResponse and isExit, were generated the same way on 2026-09-05, for
    // Level-10, so that a window can use the same commands as the console.
    // The assertions that check each undo path left the agenda as the command
    // found it were generated the same way on 2026-09-10, for A-Assertions.
    // describeTotal was extracted the same way on 2026-09-10, for
    // A-CodeQuality, when I noticed the two confirmations worded the total
    // differently.
    // numberMatching, and the rewrite of listTasks and findTasks to use it,
    // were generated the same way on 2026-09-10, for A-Streams.
    // ---------------------------------------------------------------------

    /** The one way in and out for anything the user sees or types. */
    private final Ui ui;

    /** The agenda on disk. */
    private final Storage storage;

    /**
     * The agenda in memory.
     * <p>
     * It is replaced, not filled, once storage has been asked for its
     * contents, so it cannot be {@code final}.
     */
    private TaskList tasks;

    /** The deck on disk. */
    private final CardStorage cardStorage;

    /** The deck in memory. Replaced, not filled, once storage is read. */
    private CardList cards;

    /**
     * The card the user has been asked and has not yet answered, or
     * {@code null} when no question is waiting.
     * <p>
     * This is the only state the bot keeps between one command and the next.
     * It lasts exactly one line: {@code quiz} sets it, the next input clears
     * it. Keeping it that short is what stops every other command having to
     * decide what it means in the middle of a quiz.
     */
    private Card pendingCard;

    /**
     * Builds a bot that keeps its agenda in one file.
     * <p>
     * It wires the parts together and nothing else. Reading the file is left
     * to {@link #run()}, so that the user is greeted before being told
     * anything about a file, and so that building a bot cannot fail.
     *
     * @param savePath where the agenda is kept, relative to the folder the
     *                 program runs in.
     * @param cardPath where the trivia deck is kept, in its own file so that
     *                 damage to one cannot cost the other.
     */
    public GudGoi(Path savePath, Path cardPath) {
        this.ui = new Ui();
        this.storage = new Storage(savePath);
        this.tasks = new TaskList();
        this.cardStorage = new CardStorage(cardPath);
        this.cards = new CardList();
    }

    /**
     * Stores a task and builds the confirmation shared by all three add
     * commands, including the running total.
     *
     * @param task the task that was just built.
     * @return the words to show the user.
     * @throws TaskSaveException if the new list cannot be written, in which
     *                           case the task is taken out again.
     */
    private String addAndConfirm(Task task) throws TaskSaveException {
        int sizeBefore = tasks.size();
        tasks.add(task);
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            tasks.removeLast();
            // The undo has to leave the agenda exactly as the command found
            // it, because the file was never written. Anything else and the
            // list on screen no longer matches the file on disk.
            assert tasks.size() == sizeBefore
                    : "undone add left " + tasks.size() + " tasks, not " + sizeBefore;
            throw e;
        }
        assert tasks.size() == sizeBefore + 1
                : "a saved add did not grow the agenda by one";
        return "Got it. I've added this task:\n  " + task
                + "\n" + describeTotal();
    }

    /**
     * Returns the running total, worded for the number of tasks there are.
     * <p>
     * Both the add and the delete confirmations end with this sentence. It is
     * written once so that the two cannot drift apart, which they had: one
     * said "1 task" while the other said "1 task(s)".
     *
     * @return the running total as a sentence, worded for the count.
     */
    private String describeTotal() {
        return "Now you have " + tasks.size()
                + (tasks.size() == 1 ? " task" : " tasks") + " in the list.";
    }

    /**
     * Lists every stored task, numbered from 1.
     *
     * @return the numbered agenda, or a note that it is empty.
     */
    private String listTasks() {
        if (tasks.isEmpty()) {
            return "Nothing on the agenda yet.";
        }
        return numberMatching(task -> true);
    }

    /**
     * Finds the tasks whose description holds the keyword.
     * <p>
     * Each match keeps the number it has in the full agenda, not a number
     * counted from the first match. The user can therefore type
     * {@code mark 4} against what they see, rather than counting the list
     * again to find out what 4 means.
     * <p>
     * The search ignores case, because a person looking for a word rarely
     * remembers how they capitalized it.
     *
     * @param keyword the word to look for in the descriptions.
     * @return the matching tasks, or a note that nothing matched.
     */
    private String findTasks(String keyword) {
        String wanted = keyword.toLowerCase();
        String matches = numberMatching(
                task -> task.getDescription().toLowerCase().contains(wanted));
        if (matches.isEmpty()) {
            return "Nothing on the agenda matches \"" + keyword + "\".";
        }
        return "Here are the matching tasks in your list:\n" + matches;
    }

    /**
     * Numbers the tasks that pass a test, as one block of text.
     * <p>
     * The stream runs over positions rather than over the tasks themselves,
     * because the number shown against a task has to be its place in the whole
     * agenda. A stream of tasks would lose that: after a filter, the first task
     * left is no longer the first task in the list, and {@code find} would
     * number its results 1, 2, 3 while {@code mark} still expects the real
     * positions.
     *
     * @param isWanted the test a task must pass to appear.
     * @return the numbered tasks, one per line, or an empty string if none
     *         passed.
     */
    private String numberMatching(Predicate<Task> isWanted) {
        List<Task> allTasks = tasks.asList();
        // Task.toString() supplies the "[X] " or "[ ] " status box.
        return IntStream.range(0, allTasks.size())
                .filter(position -> isWanted.test(allTasks.get(position)))
                .mapToObj(position -> (position + 1) + "." + allTasks.get(position))
                .collect(Collectors.joining("\n"));
    }

    /**
     * Marks the task the user named as done, then confirms it.
     *
     * @param number the text the user gave after {@code mark}.
     * @return the words to show the user.
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         change that cannot be saved is undone first, so
     *                         the list still matches the file.
     */
    private String mark(String number)
            throws GudGoiException {
        Task task = tasks.get(Parser.parsePosition(number));
        // The task may already be done, so the undo restores what was there
        // before rather than assuming it was not done.
        boolean wasMarked = task.isMarked();
        task.mark();
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            if (!wasMarked) {
                task.unmark();
            }
            // The file was never written, so the task has to go back to the
            // state the command found it in.
            assert task.isMarked() == wasMarked
                    : "undone mark left the task in the wrong state";
            throw e;
        }
        return "Nice! I've marked this task as done:\n  " + task;
    }

    /**
     * Marks the task the user named as not done, then confirms it.
     *
     * @param number the text the user gave after {@code unmark}.
     * @return the words to show the user.
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         change that cannot be saved is undone first, so
     *                         the list still matches the file.
     */
    private String unmark(String number)
            throws GudGoiException {
        Task task = tasks.get(Parser.parsePosition(number));
        boolean wasMarked = task.isMarked();
        task.unmark();
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            if (wasMarked) {
                task.mark();
            }
            assert task.isMarked() == wasMarked
                    : "undone unmark left the task in the wrong state";
            throw e;
        }
        return "OK, I've marked this task as not done yet:\n  " + task;
    }

    /**
     * Deletes the task the user named.
     *
     * @param number the text the user gave after {@code delete}.
     * @return the words to show the user.
     * @throws GudGoiException if the text is not a number, no task sits at
     *                         that position, or the change cannot be saved. A
     *                         deletion that cannot be saved is undone, and the
     *                         task goes back where it was.
     */
    private String deleteTask(String number)
            throws GudGoiException {
        int position = Parser.parsePosition(number);
        int sizeBefore = tasks.size();
        Task task = tasks.remove(position);
        try {
            storage.save(tasks.asList());
        } catch (TaskSaveException e) {
            // The position came from this same list a moment ago, so insert
            // needs no bounds check of its own. Its assertion holds us to that.
            tasks.insert(position, task);
            assert tasks.size() == sizeBefore
                    : "undone delete left " + tasks.size() + " tasks, not " + sizeBefore;
            throw e;
        }
        return "Noted. I've removed this task:\n  " + task
                + "\n" + describeTotal();
    }

    /**
     * Carries out one line of input from the user.
     * <p>
     * The loop in {@link #run()} reads lines; this method decides what a line
     * means and does it. Anything the user got wrong leaves here as a
     * {@link GudGoiException} for the caller to report.
     * <p>
     * It returns the answer rather than printing it, because the console and
     * the window show the same words in different shapes. Every command in
     * this program answers with text, so a command that has nothing to say is
     * not a case that has to be handled.
     *
     * @param line one line the user typed, already trimmed.
     * @return the words to show the user.
     * @throws GudGoiException if the command or its arguments are unusable.
     */
    private String handle(String line) throws GudGoiException {
        // A question that is waiting takes the whole line, whatever it says.
        // The exit word is tested by the caller before this, so "bye" still
        // ends the session rather than being graded as a wrong answer.
        if (pendingCard != null) {
            return gradeAnswer(line);
        }

        String command = Parser.parseCommandWord(line);
        String rest = Parser.parseArguments(line);

        // Building the task is the Parser's answer to the command; storing it
        // and saying so is this class's.
        return switch (command) {
            case "list" -> listTasks();
            case "mark" -> mark(rest);
            case "unmark" -> unmark(rest);
            case "todo" -> addAndConfirm(Parser.parseTodo(rest));
            case "deadline" -> addAndConfirm(Parser.parseDeadline(rest));
            case "event" -> addAndConfirm(Parser.parseEvent(rest));
            case "delete" -> deleteTask(rest);
            case "find" -> findTasks(Parser.parseKeyword(rest));
            case "card" -> addCard(Parser.parseCard(rest));
            case "cards" -> listCards();
            case "deletecard" -> deleteCard(rest);
            case "quiz" -> startQuiz();
            default -> throw new CommandNotFoundException();
        };
    }

    /**
     * Stores a card and confirms it.
     *
     * @param card the card the user described.
     * @return the words to show the user.
     * @throws CardSaveException if the deck cannot be written, in which case
     *                           the card is taken out again.
     */
    private String addCard(Card card) throws CardSaveException {
        cards.add(card);
        try {
            cardStorage.save(cards.asList());
        } catch (CardSaveException e) {
            cards.removeLast();
            throw e;
        }
        return "Added this card:\n  " + card + "\nYou now have " + cards.size()
                + (cards.size() == 1 ? " card" : " cards") + " to learn.";
    }

    /**
     * Lists every card, numbered from 1, with its answer shown.
     *
     * @return the numbered deck, or a note that it is empty.
     */
    private String listCards() {
        if (cards.isEmpty()) {
            return "No cards yet. Add one with: card <question> /a <answer>";
        }

        List<Card> allCards = cards.asList();
        String numbered = IntStream.range(0, allCards.size())
                .mapToObj(position -> (position + 1) + "." + allCards.get(position))
                .collect(Collectors.joining("\n"));
        return "Here are your cards:\n" + numbered;
    }

    /**
     * Deletes the card the user named.
     *
     * @param number the text the user gave after {@code deletecard}.
     * @return the words to show the user.
     * @throws GudGoiException if the text is not a number, no card sits at that
     *                         position, or the change cannot be saved. A delete
     *                         that cannot be saved is undone.
     */
    private String deleteCard(String number) throws GudGoiException {
        int position = Parser.parsePosition(number);
        Card card = cards.remove(position);
        try {
            cardStorage.save(cards.asList());
        } catch (CardSaveException e) {
            cards.insert(position, card);
            throw e;
        }
        return "Dropped this card:\n  " + card;
    }

    /**
     * Asks one card, chosen at random, and remembers it until the next line.
     *
     * @return the question, or a note that there is nothing to be asked.
     */
    private String startQuiz() {
        if (cards.isEmpty()) {
            return "You have no cards to be quizzed on."
                    + "\nAdd one with: card <question> /a <answer>";
        }

        pendingCard = cards.pickRandom();
        return "Quiz: " + pendingCard.getQuestion() + "\nType your answer.";
    }

    /**
     * Marks the answer to the card that was waiting, then forgets it.
     * <p>
     * The answer is shown whether or not the user got it right, because a card
     * the user missed is the one they most need to read. One question is asked
     * per {@code quiz}, so the bot is never left waiting on an answer that does
     * not come.
     *
     * @param attempt the whole line the user typed.
     * @return whether it was right, and the answer either way.
     */
    private String gradeAnswer(String attempt) {
        Card asked = pendingCard;
        pendingCard = null;

        if (asked.isAnsweredBy(attempt)) {
            return "Correct.\n  " + asked.getQuestion() + " = " + asked.getAnswer()
                    + "\nType quiz for another.";
        }
        return "Not quite.\n  " + asked.getQuestion() + " = " + asked.getAnswer()
                + "\nType quiz to try again.";
    }

    /**
     * Restores the saved deck, replacing whatever this bot held before.
     * <p>
     * Like {@link #loadTasks()}, a deck that cannot be read costs the deck, not
     * the session, so the trouble comes back as words rather than as an
     * Exception.
     *
     * @return an empty string when the deck was restored, or what went wrong.
     */
    public String loadCards() {
        try {
            cards = new CardList(cardStorage.load());
            return "";
        } catch (GudGoiException e) {
            return e.getMessage();
        }
    }


    /**
     * Returns the words the bot opens with.
     * <p>
     * The console prints the greeting itself in {@link #run()}. The window has
     * to put it in a bubble, so it asks for the text instead.
     *
     * @return the greeting.
     */
    public String getGreeting() {
        return ui.getGreeting();
    }

    /**
     * Restores the saved agenda, replacing whatever this bot held before.
     * <p>
     * A file that cannot be read costs the old agenda, not the session, so the
     * trouble comes back as words rather than as an Exception. Both front ends
     * call this after they have greeted the user, so that nobody is told about
     * a save file by a bot that has not said hello.
     *
     * @return an empty string when the agenda was restored, or what went
     *         wrong, in words the user can act on.
     */
    public String loadTasks() {
        try {
            tasks = new TaskList(storage.load());
            return "";
        } catch (TaskLoadException e) {
            return e.getMessage();
        }
    }

    /**
     * Answers one line of input, for a caller that shows the answer itself.
     * <p>
     * This is the whole of what the window needs. Unlike {@link #handle},
     * nothing leaves here as an Exception: a command the user got wrong is an
     * answer like any other, because the window has nowhere else to put it.
     *
     * @param input one line the user typed, trimmed here rather than by the
     *              caller.
     * @return the words to show the user, whether the command worked or not.
     */
    public String getResponse(String input) {
        String line = input.trim();
        if (isExit(line)) {
            return ui.getFarewell();
        }

        try {
            return handle(line);
        } catch (GudGoiException e) {
            return e.getMessage();
        }
    }

    /**
     * Tells whether a line ends the session.
     * <p>
     * The console breaks its loop on this; the window closes on it. Keeping
     * the test here means the word {@code bye} is written down once.
     *
     * @param input one line the user typed.
     * @return true when the user asked to leave.
     */
    public boolean isExit(String input) {
        return input.trim().equals("bye");
    }

    /**
     * Runs one session: greets the user, restores the saved agenda, then reads
     * and carries out commands until {@code bye} or the end of input.
     * <p>
     * The agenda is read here rather than in the constructor, so that the
     * greeting comes first. A user who is told their save file was deleted
     * before the bot has said hello has no idea who is talking.
     */
    public void run() {
        ui.showBanner();
        ui.showGreeting();

        // A missing or damaged file costs the old agenda, not the session.
        String loadTrouble = loadTasks();
        if (!loadTrouble.isEmpty()) {
            ui.showError(loadTrouble);
        }

        String deckTrouble = loadCards();
        if (!deckTrouble.isEmpty()) {
            ui.showError(deckTrouble);
        }

        while (true) {
            // Ui.readCommand answers "bye" at the end of input, so this one test
            // ends the session whether the user typed bye or the input ran out.
            String line = ui.readCommand();
            if (isExit(line)) {
                break;
            }

            try {
                ui.show(handle(line));
            } catch (GudGoiException e) {
                ui.showError(e.getMessage());
            }
        }

        ui.showFarewell();
    }

    /**
     * Starts the bot.
     * <p>
     * {@link Path#of} joins the parts with the separator the host system uses,
     * so this one line works on Windows and on Linux without a change.
     *
     * @param args ignored; the bot takes no command line arguments.
     */
    public static void main(String[] args) {
        new GudGoi(Path.of("data", "saved.txt"), Path.of("data", "cards.txt")).run();
    }
}
