// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, for A-MoreOOP. The method bodies were moved
// from GudGoi, where I had written them over Level-4 to Level-8; the class,
// the split of a line into a command word and its arguments, and the header
// comments were generated. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;

import gudgoi.exception.DateFormatException;
import gudgoi.exception.DeadlineFormatException;
import gudgoi.exception.EventFormatException;
import gudgoi.exception.FindFormatException;
import gudgoi.exception.TaskNumberFormatException;
import gudgoi.exception.TodoFormatException;
import gudgoi.task.Deadline;
import gudgoi.task.Event;
import gudgoi.task.Todo;

/**
 * Turns what the user typed into something the program can act on.
 * <p>
 * It reads text and returns values. It does not hold the agenda, write to the
 * disk, or say anything to the user, so a command that is nonsense leaves here
 * as an Exception carrying the words the user needs to read.
 * <p>
 * Every method is {@code static}, because parsing remembers nothing between
 * one command and the next. An instance would carry no state, so there is
 * nothing for one to be. The cost is that this class cannot be swapped for a
 * different parser later without changing its callers, which is a trade this
 * program is small enough to accept.
 */
public class Parser {
    /**
     * The pattern the user types when a time is given, for example
     * {@code 2019-10-15 1800}.
     * <p>
     * {@code uuuu} with {@link ResolverStyle#STRICT} is what makes an
     * impossible date such as {@code 2019-02-30} an error. The lenient default
     * would quietly move it to the end of the month.
     */
    private static final DateTimeFormatter INPUT_WITH_TIME =
            DateTimeFormatter.ofPattern("uuuu-MM-dd HHmm")
            .withResolverStyle(ResolverStyle.STRICT);

    /**
     * The pattern the user types when only a date is given, for example
     * {@code 2019-10-15}.
     */
    private static final DateTimeFormatter INPUT_DATE_ONLY =
            DateTimeFormatter.ofPattern("uuuu-MM-dd")
            .withResolverStyle(ResolverStyle.STRICT);

    /** The time a deadline gets when the user gives only a date. */
    private static final LocalTime DEADLINE_DEFAULT_TIME = LocalTime.of(0, 0);

    /**
     * The time an event's end gets when the user gives only a date, so that a
     * whole-day event runs to the end of that day rather than to its start.
     */
    private static final LocalTime EVENT_END_DEFAULT_TIME = LocalTime.of(23, 59);

    /**
     * Returns the first word of the line: the command the user is asking for.
     *
     * @param line one line the user typed, already trimmed
     * @return the command word, or the whole line when it holds one word
     */
    public static String commandWord(String line) {
        return line.split(" ", 2)[0];
    }

    /**
     * Returns everything after the command word.
     *
     * @param line one line the user typed, already trimmed
     * @return the rest of the line, or an empty string when there is no rest
     */
    public static String arguments(String line) {
        String[] parts = line.split(" ", 2);
        return parts.length > 1 ? parts[1] : "";
    }

    /**
     * Reads the task number the user typed.
     * <p>
     * Only the shape of the text is judged here. Whether a task actually sits
     * at that position is {@link TaskList}'s to answer, because only the list
     * knows how long it is.
     *
     * @param number the text after {@code mark}, {@code unmark} or
     *               {@code delete}
     * @return the position, counting from 1, unchecked against any list
     * @throws TaskNumberFormatException if the text is not a readable number
     */
    public static int parsePosition(String number)
            throws TaskNumberFormatException {
        String text = number.trim();
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException e) {
            throw new TaskNumberFormatException(text);
        }
    }

    /**
     * Reads the word a {@code find} command is to search for.
     *
     * @param details the command text after {@code find}
     * @return the keyword, with surrounding blanks removed
     * @throws FindFormatException if nothing was given to search for
     */
    public static String parseKeyword(String details) throws FindFormatException {
        String keyword = details.trim();
        if (keyword.isEmpty()) {
            throw new FindFormatException();
        }
        return keyword;
    }

    /**
     * Builds a todo from the rest of a {@code todo} command.
     *
     * @param details the command text after {@code todo}, the description
     * @return the todo the user described
     * @throws TodoFormatException if no description was given
     */
    public static Todo parseTodo(String details) throws TodoFormatException {
        String description = details.trim();
        if (description.isEmpty()) {
            throw new TodoFormatException();
        }
        return new Todo(description);
    }

    /**
     * Builds a deadline from the rest of a {@code deadline} command.
     *
     * @param details the command text after {@code deadline}, in the form
     *                {@code description /by when}
     * @return the deadline the user described
     * @throws DeadlineFormatException if the description or the /by part is missing
     * @throws DateFormatException if the /by part is not a date
     */
    public static Deadline parseDeadline(String details)
            throws DeadlineFormatException, DateFormatException {
        String[] descriptionAndBy = details.split(" /by ", 2);
        if (descriptionAndBy.length < 2) {
            throw new DeadlineFormatException();
        }

        String description = descriptionAndBy[0].trim();
        String by = descriptionAndBy[1].trim();
        if (description.isEmpty() || by.isEmpty()) {
            throw new DeadlineFormatException();
        }
        return new Deadline(description, parseDateTime(by, DEADLINE_DEFAULT_TIME));
    }

    /**
     * Builds an event from the rest of an {@code event} command.
     *
     * @param details the command text after {@code event}, in the form
     *                {@code description /from start /to end}
     * @return the event the user described
     * @throws EventFormatException if a part is missing, or the end falls
     *                              before the start
     * @throws DateFormatException if the /from or /to part is not a date
     */
    public static Event parseEvent(String details)
            throws EventFormatException, DateFormatException {
        String[] descriptionAndTimes = details.split(" /from ", 2);
        if (descriptionAndTimes.length < 2) {
            throw new EventFormatException();
        }

        String[] fromAndTo = descriptionAndTimes[1].split(" /to ", 2);
        if (fromAndTo.length < 2) {
            throw new EventFormatException();
        }

        String description = descriptionAndTimes[0].trim();
        String from = fromAndTo[0].trim();
        String to = fromAndTo[1].trim();
        if (description.isEmpty() || from.isEmpty() || to.isEmpty()) {
            throw new EventFormatException();
        }

        LocalDateTime start = parseDateTime(from, DEADLINE_DEFAULT_TIME);
        LocalDateTime end = parseDateTime(to, EVENT_END_DEFAULT_TIME);
        // An event that ends before it starts was only checkable once the times
        // became real dates. An event that starts and ends at the same moment
        // is allowed; it is odd, not wrong.
        if (end.isBefore(start)) {
            throw new EventFormatException(start, end);
        }
        return new Event(description, start, end);
    }

    /**
     * Reads a date, or a date and a time, from what the user typed.
     * <p>
     * The pattern with a time is tried first. A date on its own is not an
     * error: it takes {@code defaultTime}, which is how a deadline gets
     * midnight while an event's end gets the last minute of the day. The
     * caller supplies that default, because only the caller knows which end of
     * a day it wants.
     *
     * @param text what the user wrote after {@code /by}, {@code /from} or
     *             {@code /to}
     * @param defaultTime the time to use when the text carries none
     * @return the point in time the text names
     * @throws DateFormatException if the text is neither pattern
     */
    private static LocalDateTime parseDateTime(String text, LocalTime defaultTime)
            throws DateFormatException {
        // Runs of blanks between the date and the time are collapsed, so that
        // a stray extra space is not an error the user has to hunt for.
        String trimmed = text.trim().replaceAll("\\s+", " ");
        try {
            return LocalDateTime.parse(trimmed, INPUT_WITH_TIME);
        } catch (DateTimeParseException e) {
            // Not a date with a time. It may still be a date on its own.
        }

        try {
            return LocalDate.parse(trimmed, INPUT_DATE_ONLY).atTime(defaultTime);
        } catch (DateTimeParseException e) {
            throw new DateFormatException(trimmed);
        }
    }
}
