// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, for A-MoreOOP. The method bodies were moved
// from GudGoi, where I had written them for Level-7 and Level-8; the class,
// the constructor and the change from printing to raising an Exception were
// generated. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;

import gudgoi.exception.TaskLoadException;
import gudgoi.exception.TaskSaveException;
import gudgoi.task.Deadline;
import gudgoi.task.Event;
import gudgoi.task.Task;
import gudgoi.task.Todo;

/**
 * Keeps the agenda on disk between runs.
 * <p>
 * It knows the file, the line format, and nothing else. It never prints: a
 * file it cannot read becomes a {@link TaskLoadException} and a file it cannot
 * write becomes a {@link TaskSaveException}, and the caller decides how the
 * user hears about it. That is what lets the same class serve a console today
 * and a window later.
 */
public class Storage {
    /** The file the agenda is kept in. */
    private final Path file;

    /**
     * Creates storage backed by one file.
     * <p>
     * The path arrives already built rather than as text, because a
     * {@link Path} carries the separator the host system uses while a string
     * with a slash in it does not.
     *
     * @param file where the agenda is kept, relative to the folder the program
     *             runs in
     */
    public Storage(Path file) {
        this.file = file;
    }

    /**
     * Writes the whole task list to the file, one task per line.
     * <p>
     * The file is rewritten in full rather than appended to, because a change
     * can be a deletion or a mark as easily as an addition. The list is small,
     * so the simpler approach costs nothing worth measuring.
     *
     * @param tasks the list to store, in the order it is to be read back
     * @throws TaskSaveException if the file or its folder cannot be written
     */
    public void save(List<Task> tasks) throws TaskSaveException {
        try {
            Files.createDirectories(this.file.getParent());

            List<String> lines = new ArrayList<>();
            for (Task task : tasks) {
                lines.add(task.toSaveFormat());
            }
            Files.write(this.file, lines);
        } catch (IOException e) {
            throw new TaskSaveException(e.getMessage());
        }
    }

    /**
     * Reads the stored agenda.
     * <p>
     * A missing file is normal on a first run and gives an empty list, not an
     * error.
     * <p>
     * A file with even one line that does not match the format is not trusted
     * at all. A file this program did not write may hold anything, and part of
     * an agenda read out of a damaged file is worse than no agenda, because the
     * user cannot see what is missing. Such a file is deleted.
     *
     * @return the tasks the file holds, in the order it holds them
     * @throws TaskLoadException if the file cannot be read or does not match
     *                           the format
     */
    public List<Task> load() throws TaskLoadException {
        List<Task> loaded = new ArrayList<>();
        if (!Files.exists(this.file)) {
            return loaded;
        }

        try {
            for (String line : Files.readAllLines(this.file)) {
                if (line.isBlank()) {
                    continue;
                }

                Task task = parseSavedTask(line);
                if (task == null) {
                    throw discardCorruptFile(line);
                }
                loaded.add(task);
            }
        } catch (IOException e) {
            throw new TaskLoadException("I could not read your saved agenda: "
                    + e.getMessage()
                    + "\nI have started with an empty list, and I have left the"
                    + " file alone.");
        }

        return loaded;
    }

    /**
     * Deletes a save file that does not match the format, then reports it.
     * <p>
     * The offending line is quoted, because the user may be able to see what
     * damaged it, and because a deletion the user cannot explain is alarming.
     * <p>
     * It returns the Exception rather than raising it, so that the caller reads
     * as {@code throw discardCorruptFile(line)}. The reader can then see that
     * the loop stops there.
     *
     * @param badLine the first line that could not be read
     * @return the Exception the caller is to raise
     */
    private TaskLoadException discardCorruptFile(String badLine) {
        String problem = "Your save file does not match the format I write."
                + "\nThe first line I could not read was:\n  " + badLine
                + "\nA file written before I understood dates will look like"
                + " this.";
        try {
            Files.delete(this.file);
            return new TaskLoadException(problem
                    + "\nI have deleted the file and started with an empty"
                    + " agenda.");
        } catch (IOException e) {
            return new TaskLoadException(problem
                    + "\nI could not delete it either: " + e.getMessage()
                    + "\nI have started with an empty agenda. Your next change"
                    + " will overwrite the file.");
        }
    }

    /**
     * Rebuilds one task from one line of the save file.
     * <p>
     * Writing is the task's own job, because the object already knows what it
     * is. Reading cannot be, because there is no object yet — the type letter
     * decides which class to build. That is why this factory sits here while
     * {@link Task#toSaveFormat()} sits on the task.
     *
     * @param line one line of the save file
     * @return the task the line describes, or {@code null} if the line cannot
     *         be read
     */
    private static Task parseSavedTask(String line) {
        // A separator is a | that no backslash protects. The lookbehind is what
        // keeps an escaped \| inside a description from splitting the line.
        String[] fields = line.trim().split("\\s*(?<!\\\\)\\|\\s*");
        if (fields.length < 3) {
            return null;
        }

        // The done flag is the only field with a fixed set of values, so it is
        // the cheapest place to notice that a line is not one of ours.
        if (!fields[1].equals("0") && !fields[1].equals("1")) {
            return null;
        }

        // Each type has an exact field count. A line with more fields than its
        // type allows is not a line this program wrote, so it is rejected
        // rather than read in part.
        String description = unescape(fields[2]);
        try {
            Task task = switch (fields[0]) {
            case "T" -> fields.length != 3 ? null : new Todo(description);
            case "D" -> fields.length != 4 ? null
                    : new Deadline(description, LocalDateTime.parse(fields[3]));
            case "E" -> fields.length != 5 ? null
                    : new Event(description, LocalDateTime.parse(fields[3]),
                    LocalDateTime.parse(fields[4]));
            default -> null;
            };

            if (task != null && fields[1].equals("1")) {
                task.mark();
            }
            return task;
        } catch (DateTimeParseException e) {
            // A time field that is not in the ISO form did not come from this
            // program. A file written before Level-8 lands here.
            return null;
        }
    }

    /**
     * Returns the original text of a field read from the save file, undoing
     * {@link Task#escape(String)}.
     *
     * @param field one field of a save-file line, as it was stored
     * @return the text the user typed
     */
    private static String unescape(String field) {
        return field.replace("\\|", "|");
    }
}
