// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, for A-MoreOOP. The bounds check inside get and
// remove is my Level-5 code, moved from taskAt in GudGoi; the class, the
// constructors and the rest were generated. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import gudgoi.exception.OutOfBoundException;
import gudgoi.task.Task;

/**
 * The agenda: the tasks, in the order the user added them.
 * <p>
 * Positions here are the numbers the user types, counting from 1. The list
 * indexes from 0, and this class is the only place that has to remember the
 * difference. A position that points nowhere is an
 * {@link OutOfBoundException}, because only this class knows how many tasks
 * there are.
 * <p>
 * It changes the list and nothing else. It does not print, does not save, and
 * does not read what the user typed. Those belong to {@link Ui},
 * {@link Storage} and the caller.
 */
public class TaskList {
    /** The tasks, indexed from 0 inside this class only. */
    private final ArrayList<Task> tasks;

    /** Creates an empty agenda, for a first run or a discarded save file. */
    public TaskList() {
        this.tasks = new ArrayList<>();
    }

    /**
     * Creates an agenda holding the tasks that were read from storage.
     * <p>
     * The tasks are copied into a list of this class's own, so that whatever
     * {@link Storage} handed over cannot change underneath it later.
     *
     * @param initial the tasks to start with, in order.
     */
    public TaskList(List<Task> initial) {
        this.tasks = new ArrayList<>(initial);
    }

    /**
     * Returns how many tasks the agenda holds.
     *
     * @return the number of tasks.
     */
    public int size() {
        return this.tasks.size();
    }

    /**
     * Returns whether the agenda holds nothing.
     *
     * @return true if there are no tasks.
     */
    public boolean isEmpty() {
        return this.tasks.isEmpty();
    }

    /**
     * Adds a task to the end of the agenda.
     *
     * @param task the task to add.
     */
    public void add(Task task) {
        this.tasks.add(task);
    }

    /**
     * Returns the task at the position the user named.
     *
     * @param position the number the user typed, counting from 1.
     * @return the task sitting there.
     * @throws OutOfBoundException if no task sits at that position.
     */
    public Task get(int position) throws OutOfBoundException {
        checkPosition(position);
        return this.tasks.get(position - 1);
    }

    /**
     * Takes the task at the position the user named out of the agenda.
     *
     * @param position the number the user typed, counting from 1.
     * @return the task that was removed.
     * @throws OutOfBoundException if no task sits at that position.
     */
    public Task remove(int position) throws OutOfBoundException {
        checkPosition(position);
        return this.tasks.remove(position - 1);
    }

    /**
     * Puts a task back at the position it came from.
     * <p>
     * It exists so that a delete that could not be saved can be undone, and
     * the agenda on screen still matches the file. It takes no position it has
     * not held before, so it does not check the bounds.
     *
     * @param position where the task sat, counting from 1.
     * @param task the task to put back.
     */
    public void insert(int position, Task task) {
        this.tasks.add(position - 1, task);
    }

    /**
     * Takes the most recently added task out again.
     * <p>
     * Like {@link #insert}, it exists to undo a change that could not be
     * saved. It does nothing to an empty agenda.
     */
    public void removeLast() {
        if (!this.tasks.isEmpty()) {
            this.tasks.remove(this.tasks.size() - 1);
        }
    }

    /**
     * Returns the tasks for reading: to write them out, or to number them on
     * the screen.
     * <p>
     * The list cannot be changed through the view it returns. Anything that
     * changes the agenda goes through the methods above, so this class stays
     * the only place that decides what the agenda holds.
     *
     * @return the tasks in order, read-only.
     */
    public List<Task> asList() {
        return Collections.unmodifiableList(this.tasks);
    }

    /**
     * Raises the Exception if the position names no task.
     *
     * @param position the number the user typed, counting from 1.
     * @throws OutOfBoundException if no task sits there.
     */
    private void checkPosition(int position) throws OutOfBoundException {
        if (position < 1 || position > this.tasks.size()) {
            throw new OutOfBoundException(position, this.tasks.size());
        }
    }
}
