// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, for A-MoreOOP. The method bodies were moved
// unchanged from GudGoi, where I had written them over Level-0 to Level-7.
// I reviewed the code before committing it.
// The greeting and the farewell were moved into constants the same way on
// 2026-09-05, for Level-10, so that the window and the console can say the
// same words without one copying the other.
// ---------------------------------------------------------------------

package gudgoi;

/**
 * Everything the bot says to the console, and everything it hears back.
 * <p>
 * The rest of the program decides <em>what</em> to tell the user. This class
 * decides <em>how</em> it looks on a console: the divider lines, the banner,
 * the blank line after each response. Nothing outside this class writes to the
 * screen or reads from the keyboard.
 * <p>
 * The window built for Level-10 does not use the {@code show} methods, because
 * a divider drawn out of underscores means nothing in a chat bubble. It does
 * use {@link #getGreeting()} and {@link #getFarewell()}, so the words the bot
 * opens and closes with are written once and shown by both front ends.
 */
public class Ui {
    /** Horizontal rule printed above and below every response. */
    private static final String DIVIDER =
            "____________________________________________________________";

    /** The opening words, said by the console and by the window alike. */
    private static final String GREETING =
            "Hello, I am the Gud Goi, your friendly neighbourhood pro-ISR bot.\n"
            + "What's on the agenda today?";

    /** The closing words, said by the console and by the window alike. */
    private static final String FAREWELL =
            "Bhai bhai. Even from afar, I'm always watching.";

    /** Prints the name of the bot as block letters. */
    public void showBanner() {
        System.out.println(
                "   ___           _   _      _     ___      _ \n"
                + "  / _ \\_   _  __| | | |_/\\_| |   / _ \\___ (_)\n"
                + " / /_\\/ | | |/ _` | | \\    / |  / /_\\/ _ \\| |\n"
                + "/ /_\\\\| |_| | (_| | | /_  _\\ | / /_\\\\ (_) | |\n"
                + "\\____/ \\__,_|\\__,_| |_| \\/ |_| \\____/\\___/|_|\n"
        );
    }

    /**
     * Returns the opening words, without printing them.
     * <p>
     * The window needs the text rather than the act of printing it, because it
     * puts the words in a bubble instead of on standard output.
     *
     * @return the greeting, with no divider and no trailing blank line.
     */
    public String getGreeting() {
        return GREETING;
    }

    /** Prints the opening words, before the first command is read. */
    public void showGreeting() {
        System.out.println(GREETING + "\n");
    }

    /**
     * Returns the closing words, without printing them.
     *
     * @return the farewell, with no divider and no trailing blank line.
     */
    public String getFarewell() {
        return FAREWELL;
    }

    /** Prints the closing words, after the last command. */
    public void showFarewell() {
        System.out.println(FAREWELL + "\n");
    }

    /**
     * Prints one response, wrapped in divider lines.
     * Every line of {@code body} is printed separately, so a multi-line
     * response such as the task list stays aligned.
     *
     * @param body text to show, using {@code \n} to separate lines.
     */
    public void show(String body) {
        System.out.println(DIVIDER);
        for (String line : body.split("\n")) {
            System.out.println(line);
        }
        System.out.println(DIVIDER + "\n");
    }

    /**
     * Prints something that went wrong.
     * <p>
     * It looks the same as any other response today. It has its own method
     * because the caller's intent is different, and because an error may later
     * want to look different without a hunt through every call site.
     *
     * @param message what went wrong, in words the user can act on.
     */
    public void showError(String message) {
        show(message);
    }

    /**
     * Reads one command from the user, with surrounding spaces removed.
     * <p>
     * End of input counts as {@code bye}: when there is nothing left to read,
     * there is nobody left to talk to. Handling it here means the rest of the
     * program never sees a null line.
     *
     * @return the next command, or {@code "bye"} once input has ended.
     */
    public String readCommand() {
        String line = IO.readln();
        return line == null ? "bye" : line.trim();
    }
}
