// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension, from my decision
// that a card is its own kind of thing rather than a fourth kind of task.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

/**
 * One thing the user is trying to memorize: a question and its answer.
 * <p>
 * A card is deliberately not a {@link gudgoi.task.Task}. It has no date, it is
 * never done, and the thing that would look like "marked" — knowing the answer
 * — is not a property of the card at all. Sharing the task hierarchy would have
 * saved code and cost the meaning of both types.
 * <p>
 * A card holds no score. Whether the user got it right is the answer to one
 * question at one moment, and this class exists to remember the question.
 */
public class Card {
    /** What the user is asked. */
    private final String question;

    /** What counts as knowing it. */
    private final String answer;

    /**
     * Creates a card the user can be quizzed on.
     *
     * @param question what the user is asked.
     * @param answer what counts as knowing it.
     */
    public Card(String question, String answer) {
        this.question = question;
        this.answer = answer;
    }

    /**
     * Returns what the user is asked.
     *
     * @return the question.
     */
    public String getQuestion() {
        return this.question;
    }

    /**
     * Returns what counts as knowing it.
     *
     * @return the answer.
     */
    public String getAnswer() {
        return this.answer;
    }

    /**
     * Tells whether an attempt counts as the right answer.
     * <p>
     * Surrounding blanks and capitals are ignored, because a person recalling a
     * word has remembered it whether or not they typed it the way it was
     * stored. Nothing cleverer is attempted: a near miss is a miss, and the
     * user is shown the answer so they can judge for themselves.
     *
     * @param attempt what the user typed.
     * @return true if the attempt matches the answer.
     */
    public boolean isAnsweredBy(String attempt) {
        return attempt.trim().equalsIgnoreCase(this.answer);
    }

    /**
     * Returns the card as one line of the save file, {@code question | answer}.
     * <p>
     * A {@code |} inside either field would look like the separator when the
     * line is read back, so it is written as {@code \|}, the same way
     * {@link gudgoi.task.Task} writes its own fields.
     *
     * @return the storage form of this card.
     */
    public String toSaveFormat() {
        return escape(this.question) + " | " + escape(this.answer);
    }

    /**
     * Returns text that is safe to write as one field of a save-file line.
     *
     * @param text the raw text of one field.
     * @return the text with every {@code |} written as {@code \|}.
     */
    private static String escape(String text) {
        return text.replace("|", "\\|");
    }

    /**
     * Returns the card as the user sees it in a listing: the question, then the
     * answer in brackets.
     *
     * @return the display form of this card.
     */
    @Override
    public String toString() {
        return this.question + " (" + this.answer + ")";
    }
}
