// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension. It follows the
// shape of my own Storage class, including the full rewrite on every change
// and the refusal to trust a file that does not match the format.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import gudgoi.exception.CardLoadException;
import gudgoi.exception.CardSaveException;

/**
 * Keeps the deck on disk between runs.
 * <p>
 * It is a separate class from {@link gudgoi.Storage}, and a separate file on
 * disk, because the deck and the agenda are separate things. A user who
 * corrupts one should not lose the other.
 * <p>
 * The line format is simpler than the agenda's: every line is a card, so there
 * is no type letter and no done flag, only {@code question | answer}.
 */
public class CardStorage {
    /** How many fields a card line has. */
    private static final int FIELD_COUNT = 2;

    /** Where the question sits on a line. */
    private static final int FIELD_QUESTION = 0;

    /** Where the answer sits. */
    private static final int FIELD_ANSWER = 1;

    /** The file the deck is kept in. */
    private final Path file;

    /**
     * Creates storage backed by one file.
     *
     * @param file where the deck is kept, relative to the folder the program
     *             runs in.
     */
    public CardStorage(Path file) {
        this.file = file;
    }

    /**
     * Writes the whole deck to the file, one card per line.
     *
     * @param cards the deck to store, in the order it is to be read back.
     * @throws CardSaveException if the file or its folder cannot be written.
     */
    public void save(List<Card> cards) throws CardSaveException {
        try {
            Path parent = this.file.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }

            List<String> lines = cards.stream()
                    .map(Card::toSaveFormat)
                    .toList();
            Files.write(this.file, lines);
        } catch (IOException e) {
            throw new CardSaveException(e.getMessage());
        }
    }

    /**
     * Reads the stored deck.
     * <p>
     * A missing file is normal on a first run and gives an empty deck, not an
     * error. A file with a line that does not match the format is not trusted
     * at all, for the reason the agenda is not: half a deck is worse than none,
     * because the user cannot see which cards are missing.
     *
     * @return the cards the file holds, in the order it holds them.
     * @throws CardLoadException if the file cannot be read or does not match
     *                           the format.
     */
    public List<Card> load() throws CardLoadException {
        List<Card> loaded = new ArrayList<>();
        if (!Files.exists(this.file)) {
            return loaded;
        }

        try {
            for (String line : Files.readAllLines(this.file)) {
                if (line.isBlank()) {
                    continue;
                }

                Card card = parseSavedCard(line);
                if (card == null) {
                    throw discardCorruptFile(line);
                }
                loaded.add(card);
            }
        } catch (IOException e) {
            throw new CardLoadException("I could not read your saved cards: "
                    + e.getMessage()
                    + "\nI have started with an empty deck, and I have left the"
                    + " file alone.");
        }

        return loaded;
    }

    /**
     * Deletes a deck file that does not match the format, then reports it.
     *
     * @param badLine the first line that could not be read.
     * @return the Exception the caller is to raise.
     */
    private CardLoadException discardCorruptFile(String badLine) {
        String problem = "Your card file does not match the format I write."
                + "\nThe first line I could not read was:\n  " + badLine;
        try {
            Files.delete(this.file);
            return new CardLoadException(problem
                    + "\nI have deleted the file and started with an empty deck.");
        } catch (IOException e) {
            return new CardLoadException(problem
                    + "\nI could not delete it either: " + e.getMessage()
                    + "\nI have started with an empty deck. Your next change"
                    + " will overwrite the file.");
        }
    }

    /**
     * Rebuilds one card from one line of the deck file.
     *
     * @param line one line of the deck file.
     * @return the card the line describes, or {@code null} if the line cannot
     *         be read.
     */
    private static Card parseSavedCard(String line) {
        // A separator is a | that no backslash protects, the same rule the
        // agenda file uses.
        String[] fields = line.trim().split("\\s*(?<!\\\\)\\|\\s*");
        if (fields.length != FIELD_COUNT) {
            return null;
        }

        String question = unescape(fields[FIELD_QUESTION]);
        String answer = unescape(fields[FIELD_ANSWER]);
        if (question.isEmpty() || answer.isEmpty()) {
            return null;
        }
        return new Card(question, answer);
    }

    /**
     * Returns the original text of a field read from the deck file.
     *
     * @param field one field of a line, as it was stored.
     * @return the text the user typed.
     */
    private static String unescape(String field) {
        return field.replace("\\|", "|");
    }
}
