// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension. It follows the
// shape of my own TaskList, including the positions-from-1 rule and the
// bounds check, applied to cards. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import gudgoi.exception.OutOfBoundException;

/**
 * The deck: the cards the user is learning, in the order they were added.
 * <p>
 * It follows {@link gudgoi.TaskList} deliberately. Positions are the numbers
 * the user types, counting from 1, and this class is the only place that knows
 * the list indexes from 0. A reader who has understood one of the two
 * understands the other.
 * <p>
 * The one thing it has that a task list does not is {@link #pickRandom}, since
 * a deck exists to be drawn from.
 */
public class CardList {
    /** The cards, indexed from 0 inside this class only. */
    private final ArrayList<Card> cards;

    /**
     * Where a random card comes from.
     * <p>
     * One generator is kept for the life of the deck rather than a new one per
     * draw. Two {@link Random} objects made in the same millisecond can produce
     * the same sequence, which would show up as the same card twice.
     */
    private final Random random = new Random();

    /** Creates an empty deck, for a first run or a discarded save file. */
    public CardList() {
        this.cards = new ArrayList<>();
    }

    /**
     * Creates a deck holding the cards that were read from storage.
     *
     * @param initial the cards to start with, in order.
     */
    public CardList(List<Card> initial) {
        this.cards = new ArrayList<>(initial);
    }

    /**
     * Returns how many cards the deck holds.
     *
     * @return the number of cards.
     */
    public int size() {
        return this.cards.size();
    }

    /**
     * Returns whether the deck holds nothing.
     *
     * @return true if there are no cards.
     */
    public boolean isEmpty() {
        return this.cards.isEmpty();
    }

    /**
     * Adds a card to the end of the deck.
     *
     * @param card the card to add.
     */
    public void add(Card card) {
        this.cards.add(card);
    }

    /**
     * Takes the card at the position the user named out of the deck.
     *
     * @param position the number the user typed, counting from 1.
     * @return the card that was removed.
     * @throws OutOfBoundException if no card sits at that position.
     */
    public Card remove(int position) throws OutOfBoundException {
        if (position < 1 || position > this.cards.size()) {
            throw new OutOfBoundException(position, this.cards.size(), "card");
        }
        return this.cards.remove(position - 1);
    }

    /**
     * Puts a card back at the position it came from.
     * <p>
     * Like {@link gudgoi.TaskList#insert}, it exists so that a delete that
     * could not be saved can be undone. It takes no position it has not held
     * before, so a position that names nothing here is this program's mistake.
     *
     * @param position where the card sat, counting from 1.
     * @param card the card to put back.
     */
    public void insert(int position, Card card) {
        assert position >= 1 && position <= this.cards.size() + 1
                : "insert at " + position + " into a deck of " + this.cards.size();
        this.cards.add(position - 1, card);
    }

    /**
     * Takes the most recently added card out again, to undo an add that could
     * not be saved.
     */
    public void removeLast() {
        assert !this.cards.isEmpty() : "removeLast on an empty deck";
        this.cards.remove(this.cards.size() - 1);
    }

    /**
     * Returns a card to be quizzed on, chosen at random.
     * <p>
     * Random rather than in order, because a deck worked through from the front
     * teaches the order as much as the cards. It may draw the same card twice
     * in a row; with a small deck that is unavoidable, and refusing to would
     * mean remembering what came before, which this class does not do.
     *
     * @return one card from the deck.
     * @throws IllegalStateException if the deck is empty. The caller checks
     *                               {@link #isEmpty()} first, so reaching this
     *                               is a mistake in this program, not the
     *                               user's.
     */
    public Card pickRandom() {
        if (this.cards.isEmpty()) {
            throw new IllegalStateException("pickRandom on an empty deck");
        }
        return this.cards.get(this.random.nextInt(this.cards.size()));
    }

    /**
     * Returns the cards for reading: to write them out, or to number them on
     * the screen.
     *
     * @return the cards in order, read-only.
     */
    public List<Card> asList() {
        return Collections.unmodifiableList(this.cards);
    }
}
