// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension. I reviewed the
// code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.junit.jupiter.api.Test;

import gudgoi.exception.OutOfBoundException;

/**
 * Tests the deck: the positions it accepts, and the card it draws.
 */
public class CardListTest {

    /** Returns a deck holding one card per question given. */
    private CardList deckOf(String... questions) {
        CardList deck = new CardList();
        for (String question : questions) {
            deck.add(new Card(question, "answer of " + question));
        }
        return deck;
    }

    // ---------- positions ----------

    @Test
    public void remove_firstPosition_takesTheFirstCard() throws Exception {
        CardList deck = deckOf("a", "b");
        assertEquals("a", deck.remove(1).getQuestion());
        assertEquals(1, deck.size());
    }

    @Test
    public void remove_zero_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> deckOf("a").remove(0));
    }

    @Test
    public void remove_onePastTheEnd_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> deckOf("a").remove(2));
    }

    @Test
    public void remove_anyPositionWhenEmpty_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> new CardList().remove(1));
    }

    @Test
    public void remove_outOfBounds_reportsTheDeckInCardWording() {
        // The message must say "card", not "task": the same Exception serves
        // both lists, and the user is told which one they missed.
        OutOfBoundException thrown =
                assertThrows(OutOfBoundException.class, () -> deckOf("a").remove(5));
        assertTrue(thrown.getMessage().contains("card"));
    }

    // ---------- undoing a change that could not be saved ----------

    @Test
    public void insert_afterRemovingTheSamePosition_putsTheDeckBack() throws Exception {
        CardList deck = deckOf("a", "b", "c");
        Card removed = deck.remove(2);
        deck.insert(2, removed);

        assertEquals(3, deck.size());
        assertEquals("b", deck.asList().get(1).getQuestion());
    }

    @Test
    public void removeLast_afterAdding_undoesTheAdd() {
        CardList deck = deckOf("a");
        deck.add(new Card("b", "2"));
        deck.removeLast();

        assertEquals(1, deck.size());
        assertEquals("a", deck.asList().get(0).getQuestion());
    }

    @Test
    public void removeLast_onAnEmptyDeck_failsTheAssertion() {
        // The only caller has just added a card, so an empty deck here is this
        // program's mistake rather than the user's.
        assertThrows(AssertionError.class, new CardList()::removeLast);
    }

    // ---------- drawing a card ----------

    @Test
    public void pickRandom_oneCardDeck_alwaysDrawsThatCard() {
        assertEquals("only", deckOf("only").pickRandom().getQuestion());
    }

    @Test
    public void pickRandom_manyCards_onlyEverDrawsOneOfThem() {
        // The draw is random, so the test pins what must always hold rather
        // than which card comes back.
        CardList deck = deckOf("a", "b", "c");
        List<String> questions = List.of("a", "b", "c");
        for (int draw = 0; draw < 50; draw++) {
            assertTrue(questions.contains(deck.pickRandom().getQuestion()));
        }
    }

    @Test
    public void pickRandom_emptyDeck_throwsIllegalStateException() {
        assertThrows(IllegalStateException.class, new CardList()::pickRandom);
    }

    // ---------- what it hands out ----------

    @Test
    public void asList_theViewItReturns_cannotBeChanged() {
        List<Card> view = deckOf("a").asList();
        assertThrows(UnsupportedOperationException.class, () -> view.add(new Card("b", "2")));
    }

    @Test
    public void constructor_fromAList_copiesIt() {
        List<Card> given = new java.util.ArrayList<>(List.of(new Card("a", "1")));
        CardList deck = new CardList(given);
        given.add(new Card("b", "2"));

        assertEquals(1, deck.size());
    }
}
