// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension. I reviewed the
// code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Tests one card: what counts as knowing it, and how it is written to the file.
 */
public class CardTest {

    // ---------- what counts as the right answer ----------

    @Test
    public void isAnsweredBy_exactAnswer_isCorrect() {
        assertTrue(new Card("capital of France", "Paris").isAnsweredBy("Paris"));
    }

    @Test
    public void isAnsweredBy_differentCapitals_isStillCorrect() {
        // Someone who recalls the word has recalled it, however they typed it.
        assertTrue(new Card("capital of France", "Paris").isAnsweredBy("PARIS"));
        assertTrue(new Card("capital of France", "Paris").isAnsweredBy("paris"));
    }

    @Test
    public void isAnsweredBy_surroundingBlanks_isStillCorrect() {
        assertTrue(new Card("capital of France", "Paris").isAnsweredBy("  Paris  "));
    }

    @Test
    public void isAnsweredBy_wrongAnswer_isNotCorrect() {
        assertFalse(new Card("capital of France", "Paris").isAnsweredBy("Lyon"));
    }

    @Test
    public void isAnsweredBy_nearMiss_isNotCorrect() {
        // Nothing clever is attempted. A near miss is a miss, and the user is
        // shown the answer so they can judge it themselves.
        assertFalse(new Card("capital of France", "Paris").isAnsweredBy("Pariss"));
    }

    @Test
    public void isAnsweredBy_emptyAttempt_isNotCorrect() {
        assertFalse(new Card("capital of France", "Paris").isAnsweredBy("   "));
    }

    // ---------- how it is stored ----------

    @Test
    public void toSaveFormat_plainCard_writesBothFields() {
        assertEquals("capital of France | Paris",
                new Card("capital of France", "Paris").toSaveFormat());
    }

    @Test
    public void toSaveFormat_separatorInsideAField_isEscaped() {
        // An unescaped | would look like the field separator when read back.
        assertEquals("a \\| b | c \\| d",
                new Card("a | b", "c | d").toSaveFormat());
    }

    @Test
    public void toString_anyCard_showsQuestionThenAnswer() {
        assertEquals("capital of France (Paris)",
                new Card("capital of France", "Paris").toString());
    }
}
