// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension. It follows the
// shape of my own StorageTest, including the TempDir folder. I reviewed the
// code before committing it.
// ---------------------------------------------------------------------

package gudgoi.trivia;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import gudgoi.exception.CardLoadException;

/**
 * Tests that a deck survives a trip to disk and back, and that a file which
 * does not match the format is refused rather than half read.
 */
public class CardStorageTest {
    /** JUnit makes this folder before each test and deletes it after. */
    @TempDir
    private Path folder;

    /** Returns storage backed by a file in this test's own folder. */
    private CardStorage storageWith(String... lines) throws Exception {
        Path file = this.folder.resolve("cards.txt");
        if (lines.length > 0) {
            Files.write(file, List.of(lines));
        }
        return new CardStorage(file);
    }

    // ---------- the round trip ----------

    @Test
    public void saveThenLoad_severalCards_comeBackInOrder() throws Exception {
        CardStorage storage = storageWith();
        storage.save(List.of(new Card("one", "1"), new Card("two", "2")));

        List<Card> loaded = storage.load();
        assertEquals(2, loaded.size());
        assertEquals("one", loaded.get(0).getQuestion());
        assertEquals("2", loaded.get(1).getAnswer());
    }

    @Test
    public void saveThenLoad_separatorInsideAField_survives() throws Exception {
        // The escaping has to hold, or the fields shift and the card is wrong.
        CardStorage storage = storageWith();
        storage.save(List.of(new Card("a | b", "c | d")));

        List<Card> loaded = storage.load();
        assertEquals(1, loaded.size());
        assertEquals("a | b", loaded.get(0).getQuestion());
        assertEquals("c | d", loaded.get(0).getAnswer());
    }

    @Test
    public void saveThenLoad_emptyDeck_leavesAFileThatLoadsAsEmpty() throws Exception {
        CardStorage storage = storageWith();
        storage.save(List.of());
        assertTrue(storage.load().isEmpty());
    }

    @Test
    public void load_noFileAtAll_givesAnEmptyDeck() throws Exception {
        assertTrue(storageWith().load().isEmpty());
    }

    @Test
    public void load_blankLines_areSkipped() throws Exception {
        assertEquals(1, storageWith("one | 1", "", "   ").load().size());
    }

    // ---------- a file that is not ours ----------

    @Test
    public void load_lineWithOneField_throwsAndDeletesTheFile() throws Exception {
        CardStorage storage = storageWith("no separator here");
        assertThrows(CardLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("cards.txt")));
    }

    @Test
    public void load_lineWithTooManyFields_throwsAndDeletesTheFile() throws Exception {
        CardStorage storage = storageWith("one | two | three");
        assertThrows(CardLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("cards.txt")));
    }

    @Test
    public void load_lineWithAnEmptyField_throwsAndDeletesTheFile() throws Exception {
        // A card with no answer cannot be quizzed, so it is not one of ours.
        CardStorage storage = storageWith("question | ");
        assertThrows(CardLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("cards.txt")));
    }

    @Test
    public void load_oneBadLineAmongGoodOnes_keepsNothing() throws Exception {
        // Half a deck is worse than none: the user cannot see what is missing.
        CardStorage storage = storageWith("one | 1", "broken", "two | 2");
        assertThrows(CardLoadException.class, storage::load);
    }
}
