// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

/** The first word of the input is not a command the bot knows. */
public class CommandNotFoundException extends GudGoiException {
    /** Creates the Exception for an unrecognised command. */
    public CommandNotFoundException() {
        super("OOPS!!! I'm sorry, but I don't know what that means :-(");
    }
}
