// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: use inheritance to
// create the Level-4 task subclasses. The getTypeLetter and toSaveFormat
// methods were generated the same way on 2026-08-27, for the Level-7 save
// format. I reviewed the code before committing it.
// ---------------------------------------------------------------------

/**
 * A task that must be finished by a given time, for example
 * {@code return book /by Sunday}.
 * <p>
 * Shown to the user as {@code [D][ ] return book (by: Sunday)}.
 */
public class Deadline extends Task {
    /**
     * When the task is due.
     * Level-4 keeps this as free text; Level-8 turns it into a real date.
     */
    private final String by;

    /**
     * Creates a deadline that is not done yet.
     *
     * @param description text the user entered
     * @param by when the task is due, as the user wrote it
     */
    public Deadline(String description, String by) {
        super(description);
        this.by = by;
    }

    /**
     * Returns when this task is due.
     *
     * @return the due time, as the user wrote it
     */
    public String getBy() {
        return this.by;
    }

    @Override
    protected String getTypeIcon() {
        return "[D]";
    }

    @Override
    protected String getTypeLetter() {
        return "D";
    }

    @Override
    public String toSaveFormat() {
        return super.toSaveFormat() + " | " + escape(this.by);
    }

    @Override
    public String toString() {
        return super.toString() + " (by: " + this.by + ")";
    }
}
