// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: use inheritance to
// create the Level-4 task subclasses. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

/**
 * A task that runs between two times, for example
 * {@code project meeting /from Mon 2pm /to 4pm}.
 * <p>
 * Shown to the user as {@code [E][ ] project meeting (from: Mon 2pm to: 4pm)}.
 */
public class Event extends Task {
    /**
     * When the event starts.
     * Level-4 keeps this as free text; Level-8 turns it into a real date.
     */
    private final String from;

    /**
     * When the event ends.
     * Level-4 keeps this as free text; Level-8 turns it into a real date.
     */
    private final String to;

    /**
     * Creates an event that is not done yet.
     *
     * @param description text the user entered
     * @param from when the event starts, as the user wrote it
     * @param to when the event ends, as the user wrote it
     */
    public Event(String description, String from, String to) {
        super(description);
        this.from = from;
        this.to = to;
    }

    /**
     * Returns when this event starts.
     *
     * @return the start time, as the user wrote it
     */
    public String getFrom() {
        return this.from;
    }

    /**
     * Returns when this event ends.
     *
     * @return the end time, as the user wrote it
     */
    public String getTo() {
        return this.to;
    }

    @Override
    protected String getTypeIcon() {
        return "[E]";
    }

    @Override
    public String toString() {
        return super.toString() + " (from: " + this.from + " to: " + this.to + ")";
    }
}
