// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. The constructor for an event that ends before it starts, and the
// updated example in the first message, were generated the same way on
// 2026-08-27, for Level-8. I reviewed the code before committing it.
// ---------------------------------------------------------------------

import java.time.LocalDateTime;

/**
 * An {@code event} command could not be turned into an event.
 * <p>
 * Two things can be wrong: a part of the command is missing, or the two times
 * are the wrong way round. Both are the user's mistake in the same command, so
 * they share one type and differ only in the message.
 */
public class EventFormatException extends GudGoiException {
    /** Creates the Exception for an event command with a part missing. */
    public EventFormatException() {
        super("OOPS!!! An event needs a description, a start and an end, like:\n"
                + "  event project meeting /from 2019-10-15 1400 /to 2019-10-15 1600");
    }

    /**
     * Creates the Exception for an event whose end falls before its start.
     * <p>
     * Both times are shown, because the user gave one of them as a date alone
     * and may not realise which end of the day it became.
     *
     * @param from when the event was said to start
     * @param to when the event was said to end
     */
    public EventFormatException(LocalDateTime from, LocalDateTime to) {
        super("OOPS!!! That event ends before it starts."
                + "\n  start: " + from.format(Task.DISPLAY_FORMAT)
                + "\n  end:   " + to.format(Task.DISPLAY_FORMAT));
    }
}
