// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

/** An {@code event} command was missing its description, /from or /to part. */
public class EventFormatException extends GudGoiException {
    /** Creates the Exception for a malformed event command. */
    public EventFormatException() {
        super("OOPS!!! An event needs a description, a start and an end, like:\n"
                + "  event project meeting /from Mon 2pm /to 4pm");
    }
}
