import java.util.ArrayList;

public class GudGoi {
    private static void printBanner() {
        System.out.println(
            "   ___           _   _      _     ___      _ \n"
            + "  / _ \\_   _  __| | | |_/\\_| |   / _ \\___ (_)\n"
            + " / /_\\/ | | |/ _` | | \\    / |  / /_\\/ _ \\| |\n"
            + "/ /_\\\\| |_| | (_| | | /_  _\\ | / /_\\\\ (_) | |\n"
            + "\\____/ \\__,_|\\__,_| |_| \\/ |_| \\____/\\___/|_|\n"
        );
    }

    private static void greet() {
        System.out.println(
            "Hello, I am the Gud Goi, your friendly neighbourhood pro-ISR bot.\n" 
            + "What's on the agenda today?\n"
        );
    }

    private static void valediction() {
        System.out.println(
            "Bhai bhai. Even from afar, I'm always watching.\n"
        );
    }

    // ---------------------------------------------------------------------
    // AI-ASSISTED CODE — CITATION
    // Much of this class was generated by Claude (Anthropic), used through
    // Claude Code, on 2026-08-20 and 2026-08-21, from the Level-2 to Level-4
    // requirements: DIVIDER, tasks, say, listTasks, mark, unmark,
    // addAndConfirm, addTodo, addDeadline, addEvent, and the command dispatch
    // in main. I reviewed the code before committing it, and rewrote parts of
    // it myself.
    // ---------------------------------------------------------------------

    /** Horizontal rule printed above and below every response. */
    private static final String DIVIDER =
            "____________________________________________________________";

    /**
     * Tasks entered so far, in the order they were added.
     * These are kept in memory only; saving to disk comes in Level-7.
     */
    private static final ArrayList<Task> tasks = new ArrayList<>();

    /**
     * Prints one response to the user, wrapped in divider lines and indented.
     * Every line of {@code body} is indented separately, so multi-line
     * responses such as the task list stay aligned.
     * <p>
     * All user-facing text goes through this one method. That keeps the
     * response format in a single place, so changing how the bot talks to the
     * user is one edit rather than a hunt through every print statement.
     *
     * @param body text to show, using {@code \n} to separate lines
     */
    private static void say(String body) {
        System.out.println(DIVIDER);
        for (String line : body.split("\n")) {
            System.out.println( line);
        }
        System.out.println(DIVIDER + "\n");
    }

    /**
     * Stores a task and prints the confirmation shared by all three add
     * commands, including the running total.
     *
     * @param task the task that was just built
     */
    private static void addAndConfirm(Task task) {
        tasks.add(task);
        say("Got it. I've added this task:\n  " + task
                + "\nNow you have " + tasks.size()
                + (tasks.size() == 1 ? " task" : " tasks") + " in the list.");
    }

    /**
     * Creates a todo from the rest of the command and stores it.
     *
     * @param details the command text after {@code todo}, the description
     */
    private static void addTodo(String details) {
        addAndConfirm(new Todo(details.trim()));
    }

    /**
     * Creates a deadline from the rest of the command and stores it.
     * Assumes a {@code /by} part is present; Level-5 adds the checks.
     *
     * @param details the command text after {@code deadline}, in the form
     *                {@code description /by when}
     */
    private static void addDeadline(String details) {
        String[] descriptionAndBy = details.split(" /by ", 2);
        addAndConfirm(new Deadline(descriptionAndBy[0].trim(), descriptionAndBy[1].trim()));
    }

    /**
     * Creates an event from the rest of the command and stores it.
     * Assumes {@code /from} and {@code /to} parts are present; Level-5 adds
     * the checks.
     *
     * @param details the command text after {@code event}, in the form
     *                {@code description /from start /to end}
     */
    private static void addEvent(String details) {
        String[] descriptionAndTimes = details.split(" /from ", 2);
        String[] fromAndTo = descriptionAndTimes[1].split(" /to ", 2);
        addAndConfirm(new Event(descriptionAndTimes[0].trim(),
                fromAndTo[0].trim(), fromAndTo[1].trim()));
    }

    /** Prints every stored task, numbered from 1. */
    private static void listTasks() {
        if (tasks.isEmpty()) {
            say("Nothing on the agenda yet.");
            return;
        }

        StringBuilder list = new StringBuilder();
        for (int i = 0; i < tasks.size(); i++) {
            // Tasks are numbered from 1 for the user, but indexed from 0 here.
            // Task.toString() supplies the "[X] " or "[ ] " status box.
            list.append(i + 1).append(".").append(tasks.get(i));
            if (i < tasks.size() - 1) {
                list.append("\n");
            }
        }
        say(list.toString());
    }

    /**
     * Marks the task at the given position as done, then confirms it.
     * Assumes the position exists; Level-5 adds the checks.
     *
     * @param index position as shown to the user, counting from 1
     */
    private static void mark(int index) {
        Task task = tasks.get(index - 1);
        task.mark();
        say("Nice! I've marked this task as done:\n  " + task);
    }

    /**
     * Marks the task at the given position as not done, then confirms it.
     * Assumes the position exists; Level-5 adds the checks.
     *
     * @param index position as shown to the user, counting from 1
     */
    private static void unmark(int index) {
        Task task = tasks.get(index - 1);
        task.unmark();
        say("OK, I've marked this task as not done yet:\n  " + task);
    }

    public static void main(String[] args) {
        printBanner();
        greet();

        String line;
        while (!(line = IO.readln().trim()).equals("bye")) {
            String[] parts = line.split(" ", 2);
            String cmd = parts[0];
            String rest = parts.length > 1 ? parts[1] : "";

            boolean toMark;
            if (cmd.equals("list")) {
                listTasks();
            } else if ((toMark = cmd.equals("mark")) || cmd.equals("unmark")) {
                if (toMark) {
                    mark(Integer.parseInt(rest));
                } else {
                    unmark(Integer.parseInt(rest));
                }
            } else {
                switch (cmd) {
                    case "todo" -> addTodo(rest);
                    case "deadline" -> addDeadline(rest);
                    case "event" -> addEvent(rest);
                }
            }
        }

        valediction();
    }
}
