import java.util.ArrayList;

public class GudGoi {
    private static void printBanner() {
        System.out.println(
            "   ___           _   _      _     ___      _ \n"
            + "  / _ \\_   _  __| | | |_/\\_| |   / _ \\___ (_)\n"
            + " / /_\\/ | | |/ _` | | \\    / |  / /_\\/ _ \\| |\n"
            + "/ /_\\\\| |_| | (_| | | /_  _\\ | / /_\\\\ (_) | |\n"
            + "\\____/ \\__,_|\\__,_| |_| \\/ |_| \\____/\\___/|_|\n"
        );
    }

    private static void greet() {
        System.out.println(
            "Hello, I am the Gud Goi, your friendly neighbourhood pro-ISR bot.\n" 
            + "What's on the agenda today?\n"
        );
    }

    private static void valediction() {
        System.out.println(
            "Bhai bhai. Even from afar, I'm always watching.\n"
        );
    }

    // ---------------------------------------------------------------------
    // AI-ASSISTED CODE — CITATION
    // The Level-2 code in this section (DIVIDER, tasks, say, addTask,
    // listTasks) and the command dispatch inside main() were generated by
    // Claude (Anthropic), used through Claude Code, on 2026-08-20, from the
    // Level-2 requirements. The later change of `tasks` to ArrayList<Task>,
    // the matching updates to addTask and listTasks, and the mark and unmark
    // methods, were generated the same way and on the same day. I reviewed the
    // code before committing it.
    // ---------------------------------------------------------------------

    /** Horizontal rule printed above and below every response. */
    private static final String DIVIDER =
            "____________________________________________________________";

    /**
     * Tasks entered so far, in the order they were added.
     * These are kept in memory only; saving to disk comes in Level-7.
     */
    private static final ArrayList<Task> tasks = new ArrayList<>();

    /**
     * Prints one response to the user, wrapped in divider lines and indented.
     * Every line of {@code body} is indented separately, so multi-line
     * responses such as the task list stay aligned.
     * <p>
     * All user-facing text goes through this one method. That keeps the
     * response format in a single place, so changing how the bot talks to the
     * user is one edit rather than a hunt through every print statement.
     *
     * @param body text to show, using {@code \n} to separate lines
     */
    private static void say(String body) {
        System.out.println(DIVIDER);
        for (String line : body.split("\n")) {
            System.out.println( line);
        }
        System.out.println(DIVIDER + "\n");
    }

    /**
     * Wraps the user's text in a {@link Task}, stores it, and confirms it.
     *
     * @param description text the user entered
     */
    private static void addTask(String description) {
        tasks.add(new Task(description));
        say("added: " + description);
    }

    /** Prints every stored task, numbered from 1. */
    private static void listTasks() {
        if (tasks.isEmpty()) {
            say("Nothing on the agenda yet.");
            return;
        }

        StringBuilder list = new StringBuilder();
        for (int i = 0; i < tasks.size(); i++) {
            // Tasks are numbered from 1 for the user, but indexed from 0 here.
            // Task.toString() supplies the "[X] " or "[ ] " status box.
            list.append(i + 1).append(".").append(tasks.get(i));
            if (i < tasks.size() - 1) {
                list.append("\n");
            }
        }
        say(list.toString());
    }

    /**
     * Marks the task at the given position as done, then confirms it.
     * Assumes the position exists; Level-5 adds the checks.
     *
     * @param index position as shown to the user, counting from 1
     */
    private static void mark(int index) {
        Task task = tasks.get(index - 1);
        task.mark();
        say("Nice! I've marked this task as done:\n  " + task);
    }

    /**
     * Marks the task at the given position as not done, then confirms it.
     * Assumes the position exists; Level-5 adds the checks.
     *
     * @param index position as shown to the user, counting from 1
     */
    private static void unmark(int index) {
        Task task = tasks.get(index - 1);
        task.unmark();
        say("OK, I've marked this task as not done yet:\n  " + task);
    }

    public static void main(String[] args) {
        printBanner();
        greet();

        String cmd;
        while (!(cmd = IO.readln().trim()).equals("bye")) {
            String[] parts = cmd.split(" ", 2);
            String word = parts[0];
            String rest = parts.length > 1 ? parts[1] : "";

            int n = 0;
            boolean isNum = false;
            try {
                n = Integer.parseInt(rest);
                isNum = true;
            } catch (NumberFormatException e) {}
            boolean toMark = false;

            if (word.equals("list")) {
                listTasks();
            } else if ((toMark = word.equals("mark") || word.equals("unmark")) && isNum) {
                if (toMark) {
                    mark(n);
                } else {
                    unmark(n);
                }
            } else {
                addTask(cmd);
            }
        }

        valediction();
    }
}
