// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, for A-MoreOOP: an Exception that lets Storage
// report a bad save file without knowing how a message reaches the user.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

/**
 * The saved agenda could not be read.
 * <p>
 * {@link Storage} raises this instead of printing, because storage has no
 * business knowing whether the user is at a console, a window, or neither.
 * The caller decides how the message is shown. The message is already written
 * for the user, so the caller only has to pass it on.
 * <p>
 * Raising it does not mean the program should stop. The agenda is empty, and
 * the user can carry on.
 */
public class TaskLoadException extends GudGoiException {
    /**
     * Creates the Exception for a save file that could not be read.
     *
     * @param message what went wrong and what happened to the file, in words
     *                the user can act on
     */
    public TaskLoadException(String message) {
        super(message);
    }
}
