// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-20, from my specification: a Task class in its
// own file with a boolean `marked` field. The getTypeIcon hook and the
// matching change to toString, added for the Level-4 subclasses, were
// generated the same way and on the same day. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

/**
 * One item on the user's agenda.
 * <p>
 * A task holds the text the user typed and whether it has been completed.
 * Tasks start off not done.
 */
public class Task {
    /** Text the user entered to describe this task. */
    private final String description;

    /** Whether the user has marked this task as done. */
    private boolean marked;

    /**
     * Creates a task that is not done yet.
     *
     * @param description text the user entered
     */
    public Task(String description) {
        this.description = description;
        this.marked = false;
    }

    /** Marks this task as done. */
    public void mark() {
        this.marked = true;
    }

    /** Marks this task as not done. */
    public void unmark() {
        this.marked = false;
    }

    /**
     * Returns whether this task is done.
     *
     * @return true if the task has been marked as done
     */
    public boolean isMarked() {
        return this.marked;
    }

    /**
     * Returns the text the user entered for this task.
     *
     * @return the task description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Returns the letter box shown before the status box, for example
     * {@code [T]}. A plain task has no letter; each subclass supplies its own.
     *
     * @return the type marker for this kind of task
     */
    protected String getTypeIcon() {
        return "";
    }

    /**
     * Returns the task as it is shown to the user: the type box, the status
     * box, then the description, for example {@code [T][X] read book}.
     * <p>
     * Subclasses that carry extra details override this and append to
     * {@code super.toString()}, so the common part stays in one place.
     *
     * @return the display form of this task
     */
    @Override
    public String toString() {
        return this.getTypeIcon() + (this.marked ? "[X] " : "[ ] ") + this.description;
    }
}
