// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension, following the
// shape of my own Level-5 Exception types. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The {@code card} command did not carry a question and an answer.
 */
public class CardFormatException extends GudGoiException {
    /** Creates the Exception, with wording that shows the form expected. */
    public CardFormatException() {
        super("OOPS!!! A card needs a question and an answer."
                + "\nTry: card what is the capital of France /a Paris");
    }
}
