// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension, following the
// shape of my own Level-5 Exception types. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The stored deck could not be read.
 * <p>
 * Like {@link TaskLoadException}, this costs the old deck rather than the
 * session: the message is shown and the bot carries on with an empty deck.
 */
public class CardLoadException extends GudGoiException {
    /**
     * Creates the Exception for a deck that could not be restored.
     *
     * @param message what went wrong, in words the user can act on.
     */
    public CardLoadException(String message) {
        super(message);
    }
}
