// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-10, for the D-Trivia extension, following the
// shape of my own Level-5 Exception types. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The deck could not be written to disk.
 * <p>
 * It is separate from {@link TaskSaveException} because the two failures are
 * about different files, and the user is told which one is in trouble.
 */
public class CardSaveException extends GudGoiException {
    /**
     * Creates the Exception for a deck that could not be stored.
     *
     * @param reason what the file system reported.
     */
    public CardSaveException(String reason) {
        super("OOPS!!! I could not save your cards: " + reason
                + "\nI have undone that change, so what you see matches the file.");
    }
}
