// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, from my specification of the Level-8 date
// handling: one Exception for text that is neither a date nor a date with a
// time. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/** Text given as a time was neither a date nor a date with a time. */
public class DateFormatException extends GudGoiException {
    /**
     * Creates the Exception for text that could not be read as a date.
     *
     * @param text what the user wrote where a date was expected
     */
    public DateFormatException(String text) {
        super("OOPS!!! I could not read \"" + text + "\" as a date."
                + "\nGive me a date, like 2019-10-15,"
                + "\nor a date and a time, like 2019-10-15 1800.");
    }
}
