// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. The example in the message was corrected by the same tool on
// 2026-09-18: it still showed the free text accepted before Level-8.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/** A {@code deadline} command was missing its description or its /by part. */
public class DeadlineFormatException extends GudGoiException {
    /** Creates the Exception for a malformed deadline command. */
    public DeadlineFormatException() {
        // The example has to be a command that actually works. Until
        // Level-8 a deadline took any text, so "/by Sunday" was correct; it
        // now needs a real date, and a message that suggests otherwise sends
        // the user straight into a second error.
        super("OOPS!!! A deadline needs a description and a time, like:\n"
                + "  deadline return book /by 2019-10-15 1800");
    }
}
