// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/** A {@code deadline} command was missing its description or its /by part. */
public class DeadlineFormatException extends GudGoiException {
    /** Creates the Exception for a malformed deadline command. */
    public DeadlineFormatException() {
        super("OOPS!!! A deadline needs a description and a time, like:\n"
                + "  deadline return book /by Sunday");
    }
}
