// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-28, for Level-9. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/** A {@code find} command arrived without anything to search for. */
public class FindFormatException extends GudGoiException {
    /** Creates the Exception for a find command with no keyword. */
    public FindFormatException() {
        super("OOPS!!! Find what? Give me a word, like:\n  find book");
    }
}
