// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * Something the user did wrong that the bot can explain and recover from.
 * <p>
 * Every Exception the bot reports extends this class, so the main loop catches
 * one type and shows {@link #getMessage()} to the user. The message is
 * written for the user to read, not for a developer.
 */
public class GudGoiException extends Exception {
    /**
     * Creates an Exception carrying a message meant for the user.
     *
     * @param message what went wrong, in the bot's own words.
     */
    public GudGoiException(String message) {
        super(message);
    }
}
