// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// The noun parameter was generated the same way on 2026-09-10, for the
// D-Trivia extension, so a deck reports a bad position in its own words.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The task number read correctly, but no task sits at that position.
 * <p>
 * Text that could not be read as a number at all is a
 * {@link TaskNumberFormatException} instead.
 */
public class OutOfBoundException extends GudGoiException {
    /**
     * Creates the Exception for a number that points outside the list.
     *
     * @param index the position the user asked for, counting from 1.
     * @param size how many tasks the list actually holds.
     */
    public OutOfBoundException(int index, int size) {
        this(index, size, "task");
    }

    /**
     * Creates the Exception for a position outside a list of something other
     * than tasks.
     *
     * @param index the position the user asked for, counting from 1.
     * @param size how many items the list actually holds.
     * @param noun what the list holds, in the singular, for example
     *             {@code card}. The plural is that word with an {@code s}.
     */
    public OutOfBoundException(int index, int size, String noun) {
        super(describe(index, size, noun));
    }

    /**
     * Returns the message that fits this particular position.
     *
     * @param index the position the user asked for.
     * @param size how many items the list holds.
     * @param noun what the list holds, in the singular.
     * @return wording that says what went wrong and what is available.
     */
    private static String describe(int index, int size, String noun) {
        if (size == 0) {
            return "OOPS!!! There is no " + noun + " " + index
                    + ". Your list is empty.";
        }
        return "OOPS!!! There is no " + noun + " " + index + ". You have "
                + size + " " + noun + (size == 1 ? "." : "s.");
    }
}
