// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The task number read correctly, but no task sits at that position.
 * <p>
 * Text that could not be read as a number at all is a
 * {@link TaskNumberFormatException} instead.
 */
public class OutOfBoundException extends GudGoiException {
    /**
     * Creates the Exception for a number that points outside the list.
     *
     * @param index the position the user asked for, counting from 1.
     * @param size how many tasks the list actually holds.
     */
    public OutOfBoundException(int index, int size) {
        super(describe(index, size));
    }

    /**
     * Returns the message that fits this particular position.
     *
     * @param index the position the user asked for.
     * @param size how many tasks the list holds.
     * @return wording that says what went wrong and what is available.
     */
    private static String describe(int index, int size) {
        if (size == 0) {
            return "OOPS!!! There is no task " + index + ". Your list is empty.";
        }
        return "OOPS!!! There is no task " + index + ". You have "
                + size + (size == 1 ? " task." : " tasks.");
    }
}
