// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/**
 * The text given where a task number was expected could not be read as a
 * number at all. Either it is not digits, or it is too large for an
 * {@code int}.
 * <p>
 * A number that reads correctly but points nowhere is an
 * {@link OutOfBoundException} instead.
 */
public class TaskNumberFormatException extends GudGoiException {
    /**
     * Creates the Exception for text that is not a usable task number,
     * choosing the wording that fits what the user actually typed.
     *
     * @param text the text the user gave where a number was expected.
     */
    public TaskNumberFormatException(String text) {
        super(describe(text));
    }

    /**
     * Returns the message that fits this particular bad input.
     *
     * @param text the text the user gave.
     * @return wording that names the real problem.
     */
    private static String describe(String text) {
        if (text.isEmpty()) {
            return "OOPS!!! Which task? Give me a number, like:\n  mark 1";
        }
        if (text.matches("[0-9]+")) {
            // All digits, so it parsed as a number and then overflowed int.
            return "OOPS!!! \"" + text + "\" is far too big to be a task number.";
        }
        return "OOPS!!! \"" + text + "\" is not a number.";
    }
}
