// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-27, from my specification: a Level-7 Exception for
// a failed write, so that a command reports the failure instead of claiming
// success. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;


/**
 * The task list could not be written to disk.
 * <p>
 * Unlike the other Exceptions here, this one does not mean the user typed
 * something wrong. It means the command was understood, was carried out in
 * memory, and then could not be stored. The command that raises it undoes its
 * own change first, so the list the user sees still matches the save file.
 * That is why the message can honestly say nothing changed.
 */
public class TaskSaveException extends GudGoiException {
    /**
     * Creates the Exception for a failed write.
     *
     * @param reason what the file system reported, usually the path it could
     *               not write.
     */
    public TaskSaveException(String reason) {
        super("OOPS!!! I could not save that change: " + reason
                + "\nSo I undid it. Nothing has changed."
                + "\nCheck that the data folder is writable, then try again.");
    }
}
