// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-21, from my specification of the Level-5 Exception
// types. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.exception;

/** A {@code todo} command arrived without a description. */
public class TodoFormatException extends GudGoiException {
    /** Creates the Exception for a malformed todo command. */
    public TodoFormatException() {
        super("OOPS!!! The description of a todo cannot be empty.");
    }
}
