// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-05, for Level-10. It follows the JavaFX tutorial
// at https://se-education.org/guides/tutorials/javaFxPart3.html, which is
// course material. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.gui;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * One turn of the conversation: what was said, beside the face that said it.
 * <p>
 * The class extends {@link HBox}, so a dialog box <em>is</em> a row rather
 * than holding one. That is what lets the window drop it straight into a
 * column of other rows, the same way it would drop in a button.
 * <p>
 * Two shapes tell the speakers apart. The user's words sit on the left of
 * their face and hug the right edge; the bot's words are mirrored. The
 * constructor is private, so a caller has to choose one of the two named
 * shapes and cannot forget which way round this box belongs.
 */
public class DialogBox extends HBox {
    /** Width and height of the face, in pixels. */
    private static final double PICTURE_SIZE = 100.0;

    /** Blank space around a row, so that bubbles do not touch each other. */
    private static final double PADDING = 5.0;

    /** Blank space between the words and the face. */
    private static final double GAP = 5.0;

    /**
     * Builds a row with the words on the left and the face on the right.
     *
     * @param text what was said.
     * @param face the picture of the speaker.
     */
    private DialogBox(String text, Image face) {
        Label words = new Label(text);
        ImageView picture = new ImageView(face);

        // A long answer, such as the task list, has to wrap rather than run off
        // the side of the window, which cannot be widened.
        words.setWrapText(true);

        // ImageView does not keep the shape of the picture unless it is told
        // to, so both sides are set and the ratio is kept on purpose.
        picture.setFitWidth(PICTURE_SIZE);
        picture.setFitHeight(PICTURE_SIZE);
        picture.setPreserveRatio(true);

        this.setAlignment(Pos.TOP_RIGHT);
        this.setSpacing(GAP);
        this.setPadding(new Insets(PADDING));
        this.getChildren().addAll(words, picture);
    }

    /**
     * Builds the row for something the user said.
     *
     * @param text what the user typed.
     * @param face the picture of the user.
     * @return the row, words first.
     */
    public static DialogBox getUserDialog(String text, Image face) {
        return new DialogBox(text, face);
    }

    /**
     * Builds the row for something the bot said.
     *
     * @param text the answer from the bot.
     * @param face the picture of the bot.
     * @return the row, mirrored so that the face comes first.
     */
    public static DialogBox getBotDialog(String text, Image face) {
        DialogBox box = new DialogBox(text, face);
        box.flip();
        return box;
    }

    /**
     * Mirrors this row: the face moves to the left, and the row hugs the left
     * edge instead of the right.
     * <p>
     * The children are copied out, reversed, and put back in one step. An HBox
     * draws its children in the order they are listed, and the list it holds is
     * the live one the screen reads, which must never show the same node twice.
     * Swapping the two in place would do exactly that for an instant.
     */
    private void flip() {
        this.setAlignment(Pos.TOP_LEFT);
        ObservableList<Node> reversed = FXCollections.observableArrayList(this.getChildren());
        FXCollections.reverse(reversed);
        this.getChildren().setAll(reversed);
    }
}
