// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This class was generated by Claude (Anthropic), used through Claude Code,
// on 2026-09-05, for Level-10, and rewritten by the same tool on 2026-09-14,
// for A-BetterGui, to follow part 4 of the JavaFX tutorial at
// https://se-education.org/guides/tutorials/javaFxPart4.html, which is
// course material. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.gui;

import java.io.IOException;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * One turn of the conversation: what was said, beside the face that said it.
 * <p>
 * The class extends {@link HBox}, so a dialog box <em>is</em> a row rather
 * than holding one. That is what lets the window drop it straight into a
 * column of other rows, the same way it would drop in a button.
 * <p>
 * Since part 4 of the tutorial the row is described in {@code DialogBox.fxml},
 * not built here. The layout names {@code fx:root} as its root element, which
 * lets this object set <em>itself</em> as both the root and the controller.
 * Without that, the loader would make a second HBox and every box would need
 * a controller object of its own.
 * <p>
 * Two shapes tell the speakers apart. The user's words sit on the left of
 * their face and hug the right edge; the bot's words are mirrored. The
 * constructor is private, so a caller has to choose one of the two named
 * shapes and cannot forget which way round this box belongs.
 */
public class DialogBox extends HBox {
    /** The layout of one row, read once for each box that is made. */
    private static final String LAYOUT = "/view/DialogBox.fxml";

    /** The words, filled in by FXML. */
    @FXML
    private Label dialog;

    /** The face of whoever said them, filled in by FXML. */
    @FXML
    private ImageView displayPicture;

    /**
     * Builds a row with the words on the left and the face on the right.
     *
     * @param text what was said.
     * @param face the picture of the speaker.
     */
    private DialogBox(String text, Image face) {
        try {
            FXMLLoader loader = new FXMLLoader(MainWindow.class.getResource(LAYOUT));
            loader.setController(this);
            loader.setRoot(this);
            loader.load();
        } catch (IOException e) {
            // The layout is packaged inside the JAR. If it cannot be read the
            // build is broken, and no bubble can be drawn at all.
            throw new IllegalStateException("The dialog box layout could not be read", e);
        }

        dialog.setText(text);
        displayPicture.setImage(face);
    }

    /**
     * Builds the row for something the user said.
     *
     * @param text what the user typed.
     * @param face the picture of the user.
     * @return the row, words first.
     */
    public static DialogBox getUserDialog(String text, Image face) {
        return new DialogBox(text, face);
    }

    /**
     * Builds the row for something the bot said.
     *
     * @param text the answer from the bot.
     * @param face the picture of the bot.
     * @return the row, mirrored so that the face comes first.
     */
    public static DialogBox getBotDialog(String text, Image face) {
        DialogBox box = new DialogBox(text, face);
        box.flip();
        return box;
    }

    /**
     * Mirrors this row: the face moves to the left, and the row hugs the left
     * edge instead of the right.
     * <p>
     * The children are copied out, reversed, and put back in one step. An HBox
     * draws its children in the order they are listed, and the list it holds is
     * the live one the screen reads, which must never show the same node twice.
     * Swapping the two in place would do exactly that for an instant.
     */
    private void flip() {
        this.setAlignment(Pos.TOP_LEFT);
        ObservableList<Node> reversed = FXCollections.observableArrayList(this.getChildren());
        FXCollections.reverse(reversed);
        this.getChildren().setAll(reversed);
    }
}
