// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-05, for Level-10. It follows the JavaFX tutorial
// at https://se-education.org/guides/tutorials/javaFxPart3.html, which is
// course material. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.gui;

import javafx.application.Application;

/**
 * Starts the window, and does nothing else.
 * <p>
 * The class exists to get around a check in the JVM. JavaFX is no longer part
 * of the JDK: it arrives as a set of modules, which this project puts on the
 * class path. When the class named at start-up extends
 * {@link javafx.application.Application}, the JVM looks for those modules on
 * the <em>module</em> path instead, does not find them, and stops with
 * "JavaFX runtime components are missing".
 * <p>
 * This class does not extend {@code Application}, so the check never runs. It
 * starts JavaFX by hand from inside a JVM that is already up, where the check
 * has no say. That is why {@code build.gradle} names this class and not
 * {@link MainWindow}.
 */
public class Launcher {
    /**
     * Starts the window.
     *
     * @param args ignored; the bot takes no command line arguments.
     */
    public static void main(String[] args) {
        Application.launch(MainWindow.class, args);
    }
}
