// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-14, for A-BetterGui. It follows part 4 of the
// JavaFX tutorial at
// https://se-education.org/guides/tutorials/javaFxPart4.html, which is
// course material. The save paths and the window title were moved here from
// the hand-written MainWindow. The smallest usable window size was added
// by the same tool on 2026-09-15, following part 5 of the tutorial at
// https://se-education.org/guides/tutorials/javaFxPart5.html.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.gui;

import java.io.IOException;
import java.nio.file.Path;

import gudgoi.GudGoi;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

/**
 * Builds the window from its FXML description and puts the bot inside it.
 * <p>
 * The class does three things and no more: it loads the layout, it makes the
 * one {@link GudGoi} the session uses, and it hands that bot to the controller.
 * Everything about how the conversation behaves belongs to {@link MainWindow}.
 * <p>
 * The split exists because the layout is now data, not code. A person can open
 * {@code MainWindow.fxml} in Scene Builder and move a control without reading
 * any Java at all.
 */
public class Main extends Application {
    /** Where the agenda is kept, matching the console version exactly. */
    private static final Path SAVE_PATH = Path.of("data", "saved.txt");

    /** Where the trivia deck is kept, matching the console version exactly. */
    private static final Path CARD_PATH = Path.of("data", "cards.txt");

    /** The layout of the window, read at start-up. */
    private static final String LAYOUT = "/view/MainWindow.fxml";

    /**
     * The narrowest the window may be made.
     * <p>
     * Below this the Send button starts to eat the box the user types into.
     */
    private static final double MIN_WIDTH = 300.0;

    /**
     * The shortest the window may be made.
     * <p>
     * Below this the input row is all that is left, and the conversation it
     * belongs to is not visible at all.
     */
    private static final double MIN_HEIGHT = 200.0;

    /** The bot itself, the same class the console runs. */
    private final GudGoi gudGoi = new GudGoi(SAVE_PATH, CARD_PATH);

    /**
     * Shows the window and starts the conversation.
     * <p>
     * JavaFX calls this once, on its own thread, after the runtime is up.
     * The bot is handed over after the layout is loaded, because the
     * controller does not exist until then.
     *
     * @param stage the window, made by JavaFX but still empty and hidden.
     */
    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader loader = new FXMLLoader(Main.class.getResource(LAYOUT));
            AnchorPane root = loader.load();

            stage.setScene(new Scene(root));
            stage.setTitle("Gud Goi");

            // The window may now be resized. Every control in the layout is
            // anchored to an edge, so the conversation takes whatever room is
            // given to it. A floor is still needed: a window small enough to
            // hide its own input box cannot be typed into.
            stage.setMinWidth(MIN_WIDTH);
            stage.setMinHeight(MIN_HEIGHT);
            stage.show();

            // Only now does the controller exist, so only now can it be given
            // the bot. Greeting the user is the controller's own job, and it
            // starts as soon as it has something to greet the user with.
            loader.<MainWindow>getController().setGudGoi(gudGoi);
        } catch (IOException e) {
            // The layout is packaged inside the JAR, so a failure here means a
            // broken build rather than anything the user did. There is no
            // window yet to report it in.
            System.err.println("The window layout could not be read: " + e.getMessage());
        }
    }
}
