// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-05, for Level-10. The window layout follows the
// JavaFX tutorial at https://se-education.org/guides/tutorials/javaFxPart3.html,
// which is course material. The wiring to GudGoi, the load of the saved
// agenda and the close on "bye" were written for this project. I reviewed
// the code before committing it.
// start was split into layOutWindow, wireHandlers and startSession, and the
// pixel sizes were moved into named constants, the same way on 2026-09-10,
// for A-CodeQuality.
// ---------------------------------------------------------------------

package gudgoi.gui;

import java.nio.file.Path;

import gudgoi.GudGoi;
import javafx.animation.PauseTransition;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.util.Duration;

/**
 * The chat window: the same bot as the console, in a different set of clothes.
 * <p>
 * The window owns no rules about tasks, dates or files. It reads a line, hands
 * it to {@link GudGoi#getResponse(String)}, and puts the two sides of the
 * exchange on the screen. Everything the console version can do, this can do,
 * because both go through the same commands.
 * <p>
 * Nothing here is a loop. After {@link #start} returns, JavaFX waits, and the
 * program moves again only when the user clicks Send or presses Enter.
 */
public class MainWindow extends Application {
    /** Where the agenda is kept, matching the console version exactly. */
    private static final Path SAVE_PATH = Path.of("data", "saved.txt");

    /** Where the trivia deck is kept, matching the console version exactly. */
    private static final Path CARD_PATH = Path.of("data", "cards.txt");

    /** Size of the window, which the user cannot change. */
    private static final double WINDOW_WIDTH = 400.0;

    /** Height of the window, which the user cannot change. */
    private static final double WINDOW_HEIGHT = 600.0;

    /** Width of the conversation area, inside the window's own width. */
    private static final double SCROLL_WIDTH = 385.0;

    /** Height of the conversation area, leaving room for the input row. */
    private static final double SCROLL_HEIGHT = 535.0;

    /** Width of the box the user types into. */
    private static final double INPUT_WIDTH = 325.0;

    /** Width of the Send button, filling the rest of the input row. */
    private static final double SEND_BUTTON_WIDTH = 55.0;

    /** Gap between a control and the window edge it is anchored to. */
    private static final double EDGE_GAP = 1.0;

    /** The scroll position that shows the newest message. */
    private static final double SCROLL_TO_BOTTOM = 1.0;

    /**
     * How long the farewell stays on the screen before the window closes.
     * <p>
     * Closing at once would take the last words away before they are read.
     */
    private static final Duration FAREWELL_PAUSE = Duration.seconds(1.5);

    /**
     * The faces, shrunk as they are read rather than on every frame.
     * <p>
     * The last two arguments ask for the shape to be kept and for the good
     * filter. 200 is asked for although 100 is shown, to leave room for a
     * screen that draws more pixels than it counts.
     */
    private final Image userFace = new Image(
            this.getClass().getResourceAsStream("/images/DaUser.jpg"), 200, 200, true, true);

    /** The face of the bot. */
    private final Image botFace = new Image(
            this.getClass().getResourceAsStream("/images/DaDuke.jpg"), 200, 200, true, true);

    /** The bot itself, the same class the console runs. */
    private final GudGoi gudGoi = new GudGoi(SAVE_PATH, CARD_PATH);

    /** The conversation so far, one dialog box for each turn. */
    private final VBox dialogContainer = new VBox();

    /** The box the user types into. */
    private final TextField userInput = new TextField();

    /** The button that sends what was typed. */
    private final Button sendButton = new Button("Send");

    /** The conversation area, which scrolls as the conversation grows. */
    private final ScrollPane scrollPane = new ScrollPane();

    /**
     * Builds the window and starts the session.
     * <p>
     * JavaFX calls this once, on its own thread, after the runtime is up.
     *
     * @param stage the window, made by JavaFX but still empty and hidden.
     */
    @Override
    public void start(Stage stage) {
        layOutWindow(stage);
        wireHandlers();
        stage.show();
        startSession();
    }

    /**
     * Puts the controls in the window and gives each one its size and place.
     *
     * @param stage the window to fill.
     */
    private void layOutWindow(Stage stage) {
        scrollPane.setContent(dialogContainer);

        AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);

        stage.setScene(new Scene(mainLayout));
        stage.setTitle("Gud Goi");
        stage.setResizable(false);
        stage.setMinHeight(WINDOW_HEIGHT);
        stage.setMinWidth(WINDOW_WIDTH);

        mainLayout.setPrefSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        scrollPane.setPrefSize(SCROLL_WIDTH, SCROLL_HEIGHT);
        scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.ALWAYS);
        scrollPane.setVvalue(SCROLL_TO_BOTTOM);
        scrollPane.setFitToWidth(true);
        dialogContainer.setPrefHeight(Region.USE_COMPUTED_SIZE);
        userInput.setPrefWidth(INPUT_WIDTH);
        sendButton.setPrefWidth(SEND_BUTTON_WIDTH);

        AnchorPane.setTopAnchor(scrollPane, EDGE_GAP);
        AnchorPane.setBottomAnchor(sendButton, EDGE_GAP);
        AnchorPane.setRightAnchor(sendButton, EDGE_GAP);
        AnchorPane.setLeftAnchor(userInput, EDGE_GAP);
        AnchorPane.setBottomAnchor(userInput, EDGE_GAP);
    }

    /** Says what each control does when the user acts on it. */
    private void wireHandlers() {
        // Both ways of sending lead to the same place, so that the mouse and
        // the keyboard are equally good.
        sendButton.setOnMouseClicked(event -> handleUserInput());
        userInput.setOnAction(event -> handleUserInput());

        // The height changes only after the new rows have been laid out, which
        // is later than the moment they are added. Watching the height is
        // therefore the only way to scroll to a bottom that already exists.
        dialogContainer.heightProperty()
                .addListener(observable -> scrollPane.setVvalue(SCROLL_TO_BOTTOM));
    }

    /**
     * Greets the user, then restores the saved agenda.
     * <p>
     * The greeting comes before the file is read, for the reason the console
     * has: a user told about a save file by a bot that has not introduced
     * itself does not know who is talking.
     */
    private void startSession() {
        showBotSaying(gudGoi.getGreeting());
        String loadTrouble = gudGoi.loadTasks();
        if (!loadTrouble.isEmpty()) {
            showBotSaying(loadTrouble);
        }

        String deckTrouble = gudGoi.loadCards();
        if (!deckTrouble.isEmpty()) {
            showBotSaying(deckTrouble);
        }
    }

    /**
     * Answers one line from the user, and adds both sides to the conversation.
     * <p>
     * An empty line is ignored, because a stray Enter is not a command and an
     * empty bubble says nothing. This runs on the JavaFX thread, the only one
     * allowed to touch the screen, so it has to stay quick.
     */
    private void handleUserInput() {
        String typed = userInput.getText();
        if (typed.trim().isEmpty()) {
            userInput.clear();
            return;
        }

        dialogContainer.getChildren().add(DialogBox.getUserDialog(typed, userFace));
        showBotSaying(gudGoi.getResponse(typed));
        userInput.clear();

        if (gudGoi.isExit(typed)) {
            closeAfterFarewell();
        }
    }

    /** Adds one bubble from the bot to the conversation. */
    private void showBotSaying(String words) {
        dialogContainer.getChildren().add(DialogBox.getBotDialog(words, botFace));
    }

    /**
     * Shuts the window down once the farewell has been read.
     * <p>
     * Typing is switched off first, so that the session cannot be carried on
     * after the bot has said goodbye.
     */
    private void closeAfterFarewell() {
        userInput.setDisable(true);
        sendButton.setDisable(true);

        PauseTransition wait = new PauseTransition(FAREWELL_PAUSE);
        wait.setOnFinished(event -> Platform.exit());
        wait.play();
    }
}
