// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This class was generated by Claude (Anthropic), used through Claude Code,
// on 2026-09-05, for Level-10, and rewritten by the same tool on 2026-09-14,
// for A-BetterGui, to follow part 4 of the JavaFX tutorial at
// https://se-education.org/guides/tutorials/javaFxPart4.html, which is
// course material. The layout moved out to MainWindow.fxml; the session
// start, the empty-line guard and the close on "bye" are this project's own
// and were kept unchanged. On 2026-09-15, the same tool added the error
// flag that showBotSaying passes on, following part 5 of the tutorial at
// https://se-education.org/guides/tutorials/javaFxPart5.html, which styles
// a reply by the kind of command that caused it.
// I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi.gui;

import gudgoi.GudGoi;
import javafx.animation.PauseTransition;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import javafx.util.Duration;

/**
 * The controller for the chat window: the same bot as the console, in a
 * different set of clothes.
 * <p>
 * The class owns no rules about tasks, dates or files, and since part 4 of the
 * tutorial it owns no sizes or positions either — those live in
 * {@code MainWindow.fxml}. It reads a line, hands it to
 * {@link GudGoi#getResponse(String)}, and puts the two sides of the exchange
 * on the screen.
 * <p>
 * The class does not extend a layout class. It never builds one: FXML builds
 * the {@code AnchorPane} and passes it to {@link Main}, and this object is
 * only the thing that answers the controls in it.
 * <p>
 * Nothing here is a loop. After the window is shown, JavaFX waits, and the
 * program moves again only when the user clicks Send or presses Enter.
 */
public class MainWindow {
    /**
     * How long the farewell stays on the screen before the window closes.
     * <p>
     * Closing at once would take the last words away before they are read.
     */
    private static final Duration FAREWELL_PAUSE = Duration.seconds(1.5);

    /** The conversation area, which scrolls as the conversation grows. */
    @FXML
    private ScrollPane scrollPane;

    /** The conversation so far, one dialog box for each turn. */
    @FXML
    private VBox dialogContainer;

    /** The box the user types into. */
    @FXML
    private TextField userInput;

    /** The button that sends what was typed. */
    @FXML
    private Button sendButton;

    /** The bot itself, handed over by {@link Main} once the layout is loaded. */
    private GudGoi gudGoi;

    /**
     * The faces, shrunk as they are read rather than on every frame.
     * <p>
     * The last two arguments ask for the shape to be kept and for the good
     * filter. 120 is asked for although 38 is shown, to leave room for a
     * screen that draws more pixels than it counts.
     */
    private final Image userFace = new Image(
            this.getClass().getResourceAsStream("/images/DaUser.jpg"), 120, 120, true, true);

    /** The face of the bot. */
    private final Image botFace = new Image(
            this.getClass().getResourceAsStream("/images/DaDuke.jpg"), 120, 120, true, true);

    /**
     * Finishes the set-up that FXML cannot describe.
     * <p>
     * FXML calls this once, after every control named in the layout has been
     * made and injected. Tying the scroll position to the height of the
     * conversation keeps the newest message in view: the height changes only
     * after the new rows are laid out, which is later than the moment they
     * are added, so watching the height is the only way to scroll to a bottom
     * that already exists.
     */
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
    }

    /**
     * Gives this window the bot it talks to, and starts the session.
     * <p>
     * The greeting comes before the file is read, for the reason the console
     * has: a user told about a save file by a bot that has not introduced
     * itself does not know who is talking.
     *
     * @param bot the bot that answers every line typed in this window.
     */
    public void setGudGoi(GudGoi bot) {
        assert bot != null : "the window cannot run without a bot";
        this.gudGoi = bot;

        showBotSaying(gudGoi.getGreeting(), false);

        // A save file that could not be read is something the user has to know
        // about and may have to act on, so it is shown the way a refused
        // command is rather than as ordinary chatter.
        String loadTrouble = gudGoi.loadTasks();
        if (!loadTrouble.isEmpty()) {
            showBotSaying(loadTrouble, true);
        }

        String deckTrouble = gudGoi.loadCards();
        if (!deckTrouble.isEmpty()) {
            showBotSaying(deckTrouble, true);
        }
    }

    /**
     * Answers one line from the user, and adds both sides to the conversation.
     * <p>
     * An empty line is ignored, because a stray Enter is not a command and an
     * empty bubble says nothing. This runs on the JavaFX thread, the only one
     * allowed to touch the screen, so it has to stay quick.
     * <p>
     * Both the Send button and the Enter key are wired to this method in the
     * layout, so that the mouse and the keyboard are equally good.
     */
    @FXML
    private void handleUserInput() {
        String typed = userInput.getText();
        if (typed.trim().isEmpty()) {
            userInput.clear();
            return;
        }

        dialogContainer.getChildren().add(DialogBox.getUserDialog(typed, userFace));

        // The answer is asked for first and judged second. wasLastAnswerAnError
        // reports on the most recent call, so the order matters.
        String answer = gudGoi.getResponse(typed);
        showBotSaying(answer, gudGoi.wasLastAnswerAnError());
        userInput.clear();

        if (gudGoi.isExit(typed)) {
            closeAfterFarewell();
        }
    }

    /**
     * Adds one bubble from the bot to the conversation.
     *
     * @param words   what the bot has to say.
     * @param isError true when the words are a refusal, which is drawn in a
     *                format of its own so that it is seen before it is read.
     */
    private void showBotSaying(String words, boolean isError) {
        dialogContainer.getChildren().add(DialogBox.getBotDialog(words, botFace, isError));
    }

    /**
     * Shuts the window down once the farewell has been read.
     * <p>
     * Typing is switched off first, so that the session cannot be carried on
     * after the bot has said goodbye.
     */
    private void closeAfterFarewell() {
        userInput.setDisable(true);
        sendButton.setDisable(true);

        PauseTransition wait = new PauseTransition(FAREWELL_PAUSE);
        wait.setOnFinished(event -> Platform.exit());
        wait.play();
    }
}
