// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-09-17, for A-MoreTesting, from my decision that the
// command layer is the part of this program with no tests at all, and that
// the quiz and the undo-on-failure paths are the two places where a mistake
// would cost the user their data. I reviewed the code before committing it.
// ---------------------------------------------------------------------

package gudgoi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Tests the command layer: one line of text in, one block of text out.
 * <p>
 * Every test here goes through {@link GudGoi#getResponse(String)}, the single
 * entry point the window uses. That is deliberate. The methods behind it are
 * private, and testing through the front door checks the thing the user
 * actually touches, including the dispatch and the order the parts run in.
 * <p>
 * Two groups matter more than the rest. The quiz is the only state the bot
 * keeps between one command and the next, so it is the only place where a line
 * can mean something other than what it says. The save-failure group checks
 * the promise that the agenda on screen always matches the file: when a write
 * fails the change is undone, so nothing is claimed that was never stored.
 */
public class GudGoiTest {

    /** A folder JUnit makes for one test and deletes afterwards. */
    @TempDir
    private Path folder;

    /** Builds a bot whose agenda and deck live in the temporary folder. */
    private GudGoi botIn(Path where) {
        return new GudGoi(where.resolve("saved.txt"), where.resolve("cards.txt"));
    }

    /**
     * Builds a bot whose agenda can never be written.
     * <p>
     * The save path is placed inside a plain file. Storage asks for the parent
     * folder to be created, and a folder cannot be created where a file
     * already sits, so every save fails. This beats a read-only folder, which
     * behaves differently on Windows, macOS and Linux.
     */
    private GudGoi botThatCannotSave(Path where) throws IOException {
        Path blocker = where.resolve("blocker");
        Files.writeString(blocker, "not a folder");
        return new GudGoi(blocker.resolve("saved.txt"), where.resolve("cards.txt"));
    }

    // ---------- adding, listing and counting ----------

    @Test
    public void getResponse_todo_confirmsItAndCountsTheAgenda() {
        GudGoi bot = botIn(folder);
        assertEquals("Got it. I've added this task:\n  [T][ ] read book"
                + "\nNow you have 1 task in the list.", bot.getResponse("todo read book"));
    }

    @Test
    public void getResponse_secondTask_countsInThePlural() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo a");
        assertTrue(bot.getResponse("todo b").endsWith("Now you have 2 tasks in the list."));
    }

    @Test
    public void list_nothingAddedYet_saysTheAgendaIsEmpty() {
        assertEquals("Nothing on the agenda yet.", botIn(folder).getResponse("list"));
    }

    @Test
    public void list_severalTasks_numbersThemFromOne() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo alpha");
        bot.getResponse("todo beta");
        assertEquals("1.[T][ ] alpha\n2.[T][ ] beta", bot.getResponse("list"));
    }

    @Test
    public void list_afterMarking_showsTheTaskAsDone() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        bot.getResponse("mark 1");
        assertEquals("1.[T][X] read book", bot.getResponse("list"));
    }

    @Test
    public void mark_aTaskThatIsThere_confirmsItAsDone() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        assertEquals("Nice! I've marked this task as done:\n  [T][X] read book",
                bot.getResponse("mark 1"));
    }

    @Test
    public void unmark_aTaskThatWasDone_putsTheBoxBack() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        bot.getResponse("mark 1");
        assertEquals("OK, I've marked this task as not done yet:\n  [T][ ] read book",
                bot.getResponse("unmark 1"));
    }

    @Test
    public void delete_theOnlyTask_removesItAndCountsDown() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        assertTrue(bot.getResponse("delete 1").endsWith("Now you have 0 tasks in the list."));
    }

    // ---------- find keeps the real position ----------

    @Test
    public void find_aMatchInTheMiddle_keepsItsPositionInTheWholeAgenda() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo alpha");
        bot.getResponse("todo beta");
        bot.getResponse("todo gamma");
        // "beta" is second in the agenda, so it must be numbered 2, not 1.
        assertEquals("Here are the matching tasks in your list:\n2.[T][ ] beta",
                bot.getResponse("find beta"));
    }

    @Test
    public void find_differentCapitals_stillMatches() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo Read Book");
        assertTrue(bot.getResponse("find read").contains("Read Book"));
    }

    @Test
    public void find_nothingMatches_saysSoAndQuotesTheWord() {
        assertEquals("Nothing on the agenda matches \"zebra\".",
                botIn(folder).getResponse("find zebra"));
    }

    // ---------- what counts as a refusal ----------

    @Test
    public void wasLastAnswerAnError_unknownCommand_isTrue() {
        GudGoi bot = botIn(folder);
        bot.getResponse("blahblah");
        assertTrue(bot.wasLastAnswerAnError());
    }

    @Test
    public void wasLastAnswerAnError_commandThatWorked_isFalse() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        assertFalse(bot.wasLastAnswerAnError());
    }

    @Test
    public void wasLastAnswerAnError_afterAFailureThenASuccess_isClearedAgain() {
        GudGoi bot = botIn(folder);
        bot.getResponse("blahblah");
        bot.getResponse("todo read book");
        assertFalse(bot.wasLastAnswerAnError());
    }

    @Test
    public void wasLastAnswerAnError_markWithNoSuchTask_isTrue() {
        GudGoi bot = botIn(folder);
        bot.getResponse("mark 7");
        assertTrue(bot.wasLastAnswerAnError());
    }

    @Test
    public void wasLastAnswerAnError_todoWithNoDescription_isTrue() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo");
        assertTrue(bot.wasLastAnswerAnError());
    }

    @Test
    public void isExit_theWordBye_endsTheSession() {
        assertTrue(botIn(folder).isExit("bye"));
    }

    @Test
    public void isExit_aWordThatMerelyStartsWithBye_doesNot() {
        assertFalse(botIn(folder).isExit("byebye"));
    }

    // ---------- the quiz: the only state kept between commands ----------

    @Test
    public void quiz_withAnEmptyDeck_saysThereIsNothingToAsk() {
        assertTrue(botIn(folder).getResponse("quiz")
                .startsWith("You have no cards to be quizzed on."));
    }

    @Test
    public void card_questionAndAnswer_isAddedAndCounted() {
        GudGoi bot = botIn(folder);
        assertEquals("Added this card:\n  capital of France (Paris)"
                + "\nYou now have 1 card to learn.",
                bot.getResponse("card capital of France /a Paris"));
    }

    @Test
    public void quiz_oneCardDeck_asksThatCard() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        assertEquals("Quiz: capital of France\nType your answer.", bot.getResponse("quiz"));
    }

    @Test
    public void quiz_thenTheRightAnswer_isGradedCorrect() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        assertEquals("Correct.\n  capital of France = Paris\nType quiz for another.",
                bot.getResponse("Paris"));
    }

    @Test
    public void quiz_thenTheWrongAnswer_stillShowsTheAnswer() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        assertEquals("Not quite.\n  capital of France = Paris\nType quiz to try again.",
                bot.getResponse("Berlin"));
    }

    @Test
    public void quiz_thenACommandWord_isGradedAsAnAnswerRatherThanRun() {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        // A question is waiting, so "list" is what the user answered, not a
        // command. The agenda must not be shown.
        assertTrue(bot.getResponse("list").startsWith("Not quite."));
    }

    @Test
    public void quiz_afterOneAnswer_theNextLineIsACommandAgain() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        bot.getResponse("Paris");
        // Grading cleared the card, so the bot listens for commands again.
        // One quiz asks exactly one question.
        assertEquals("Nothing on the agenda yet.", bot.getResponse("list"));
    }

    @Test
    public void quiz_thenBye_endsTheSessionRatherThanBeingGraded() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        // isExit runs before handle, so bye escapes a waiting question.
        assertFalse(bot.getResponse("bye").startsWith("Not quite."));
    }

    @Test
    public void quiz_gradingAWrongAnswer_isNotAnError() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        bot.getResponse("Berlin");
        // A wrong answer is a normal reply. Only a refused command is an error.
        assertFalse(bot.wasLastAnswerAnError());
    }

    @Test
    public void quiz_answerInDifferentCapitals_isStillCorrect() {
        GudGoi bot = botIn(folder);
        bot.getResponse("card capital of France /a Paris");
        bot.getResponse("quiz");
        assertTrue(bot.getResponse("  paris  ").startsWith("Correct."));
    }

    // ---------- a write that fails is undone ----------

    @Test
    public void todo_whenTheSaveFails_isReportedAsAnError() throws IOException {
        GudGoi bot = botThatCannotSave(folder);
        bot.getResponse("todo read book");
        assertTrue(bot.wasLastAnswerAnError());
    }

    @Test
    public void todo_whenTheSaveFails_isTakenBackOutOfTheAgenda() throws IOException {
        GudGoi bot = botThatCannotSave(folder);
        bot.getResponse("todo read book");
        // The file was never written, so the agenda must not show a task that
        // nothing stored.
        assertEquals("Nothing on the agenda yet.", bot.getResponse("list"));
    }

    @Test
    public void delete_whenTheSaveFails_leavesTheTaskWhereItWas() throws IOException {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");

        // Replace the save file with a folder of the same name. Writing to it
        // now fails, while the task the bot already holds is untouched.
        Path savePath = folder.resolve("saved.txt");
        Files.delete(savePath);
        Files.createDirectory(savePath);

        bot.getResponse("delete 1");
        assertTrue(bot.wasLastAnswerAnError());
    }

    @Test
    public void delete_whenTheSaveFails_theTaskIsStillListed() throws IOException {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");

        Path savePath = folder.resolve("saved.txt");
        Files.delete(savePath);
        Files.createDirectory(savePath);

        bot.getResponse("delete 1");
        // The delete was undone, so the task goes back at the position it held.
        assertEquals("1.[T][ ] read book", bot.getResponse("list"));
    }

    @Test
    public void mark_whenTheSaveFails_theTaskIsNotLeftDone() throws IOException {
        GudGoi bot = botIn(folder);
        bot.getResponse("todo read book");

        Path savePath = folder.resolve("saved.txt");
        Files.delete(savePath);
        Files.createDirectory(savePath);

        bot.getResponse("mark 1");
        assertEquals("1.[T][ ] read book", bot.getResponse("list"));
    }

    // ---------- reading a file this program did not write ----------

    @Test
    public void loadTasks_noFileAtAll_saysNothingIsWrong() {
        assertEquals("", botIn(folder).loadTasks());
    }

    @Test
    public void loadTasks_aDamagedFile_reportsItInWords() throws IOException {
        Files.writeString(folder.resolve("saved.txt"), "T | 1 | far | too | many | fields");
        assertFalse(botIn(folder).loadTasks().isEmpty());
    }

    @Test
    public void loadTasks_aDamagedFile_leavesTheAgendaEmpty() throws IOException {
        Files.writeString(folder.resolve("saved.txt"), "T | 1 | far | too | many | fields");
        GudGoi bot = botIn(folder);
        bot.loadTasks();
        assertEquals("Nothing on the agenda yet.", bot.getResponse("list"));
    }

    @Test
    public void loadCards_noFileAtAll_saysNothingIsWrong() {
        assertEquals("", botIn(folder).loadCards());
    }

    // ---------- the agenda survives a restart ----------

    @Test
    public void savedAgenda_readBackByAFreshBot_comesBackUnchanged() {
        GudGoi first = botIn(folder);
        first.getResponse("deadline submit iP /by 2026-09-18 2359");

        GudGoi second = botIn(folder);
        second.loadTasks();
        assertEquals("1.[D][ ] submit iP (by: Sep 18 2026, 23:59)", second.getResponse("list"));
    }

    // ---------- an error message must not suggest a command that fails ----------

    /**
     * Feeds the example back to the bot.
     * <p>
     * A complaint about a command format ends with an example, indented on its
     * own line. This takes that last line and runs it. If the example is not
     * itself a working command, the user is sent straight into a second error,
     * which is what the deadline message did until 18 September 2026: it still
     * showed {@code /by Sunday}, the free text that Level-8 stopped accepting.
     */
    private boolean isExampleFromComplaintAccepted(String badCommand) {
        GudGoi bot = botIn(folder);
        String complaint = bot.getResponse(badCommand);
        String example = complaint.lines().reduce((first, second) -> second).orElseThrow().trim();
        bot.getResponse(example);
        return !bot.wasLastAnswerAnError();
    }

    @Test
    public void deadlineComplaint_theExampleItShows_isAcceptedByTheParser() {
        assertTrue(isExampleFromComplaintAccepted("deadline"));
    }

    @Test
    public void eventComplaint_theExampleItShows_isAcceptedByTheParser() {
        assertTrue(isExampleFromComplaintAccepted("event"));
    }

    @Test
    public void savedDeck_readBackByAFreshBot_comesBackUnchanged() {
        GudGoi first = botIn(folder);
        first.getResponse("card capital of France /a Paris");

        GudGoi second = botIn(folder);
        second.loadCards();
        assertEquals("Here are your cards:\n1.capital of France (Paris)",
                second.getResponse("cards"));
    }
}
