// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-28, for A-JUnit. The cases come from the edge
// cases I had found by running the program by hand. I reviewed the code
// before committing it.
// ---------------------------------------------------------------------

package gudgoi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

import gudgoi.exception.DateFormatException;
import gudgoi.exception.DeadlineFormatException;
import gudgoi.exception.EventFormatException;
import gudgoi.exception.TaskNumberFormatException;
import gudgoi.exception.TodoFormatException;
import gudgoi.task.Deadline;
import gudgoi.task.Event;
import gudgoi.task.Todo;

/**
 * Tests the reading of a command.
 * <p>
 * The parser is the only class that turns text a person typed into values, so
 * it is where a mistake is most likely and where a test is cheapest: every
 * method here takes a string and returns a value, with no file and no screen
 * involved.
 */
public class ParserTest {

    // ---------- splitting the line ----------

    @Test
    public void commandWord_lineWithArguments_returnsFirstWordOnly() {
        assertEquals("deadline", Parser.commandWord("deadline read book /by 2019-10-15"));
    }

    @Test
    public void commandWord_oneWordLine_returnsThatWord() {
        assertEquals("list", Parser.commandWord("list"));
    }

    @Test
    public void arguments_oneWordLine_returnsEmptyString() {
        assertEquals("", Parser.arguments("list"));
    }

    @Test
    public void arguments_lineWithArguments_returnsEverythingAfterTheFirstWord() {
        assertEquals("read book /by 2019-10-15",
                Parser.arguments("deadline read book /by 2019-10-15"));
    }

    // ---------- todo ----------

    @Test
    public void parseTodo_description_keepsItExactly() throws Exception {
        Todo todo = Parser.parseTodo("  read book  ");
        assertEquals("[T][ ] read book", todo.toString());
    }

    @Test
    public void parseTodo_emptyDescription_throwsTodoFormatException() {
        assertThrows(TodoFormatException.class, () -> Parser.parseTodo("   "));
    }

    // ---------- deadline ----------

    @Test
    public void parseDeadline_dateOnly_timeIsMidnight() throws Exception {
        Deadline deadline = Parser.parseDeadline("submit report /by 2019-10-15");
        assertEquals(LocalDateTime.of(2019, 10, 15, 0, 0), deadline.getBy());
    }

    @Test
    public void parseDeadline_dateAndTime_timeIsAsGiven() throws Exception {
        Deadline deadline = Parser.parseDeadline("pay rent /by 2019-10-15 1800");
        assertEquals(LocalDateTime.of(2019, 10, 15, 18, 0), deadline.getBy());
    }

    @Test
    public void parseDeadline_extraBlanksBeforeTheTime_stillAccepted() throws Exception {
        Deadline deadline = Parser.parseDeadline("pay rent /by 2019-10-15    1800");
        assertEquals(LocalDateTime.of(2019, 10, 15, 18, 0), deadline.getBy());
    }

    @Test
    public void parseDeadline_leapDayInALeapYear_accepted() throws Exception {
        Deadline deadline = Parser.parseDeadline("leap /by 2020-02-29");
        assertEquals(LocalDateTime.of(2020, 2, 29, 0, 0), deadline.getBy());
    }

    @Test
    public void parseDeadline_leapDayInACommonYear_throwsDateFormatException() {
        assertThrows(DateFormatException.class,
                () -> Parser.parseDeadline("not a leap year /by 2019-02-29"));
    }

    @Test
    public void parseDeadline_dayThatCannotExist_throwsDateFormatException() {
        // A lenient parser would quietly move this to the end of February.
        assertThrows(DateFormatException.class,
                () -> Parser.parseDeadline("impossible /by 2019-02-30"));
    }

    @Test
    public void parseDeadline_dateWithoutLeadingZeros_throwsDateFormatException() {
        assertThrows(DateFormatException.class,
                () -> Parser.parseDeadline("short /by 2019-1-5"));
    }

    @Test
    public void parseDeadline_timeOutsideTheClock_throwsDateFormatException() {
        assertThrows(DateFormatException.class,
                () -> Parser.parseDeadline("late /by 2019-10-15 2500"));
    }

    @Test
    public void parseDeadline_noByPart_throwsDeadlineFormatException() {
        assertThrows(DeadlineFormatException.class,
                () -> Parser.parseDeadline("read book"));
    }

    @Test
    public void parseDeadline_byPartEmpty_throwsDeadlineFormatException() {
        assertThrows(DeadlineFormatException.class,
                () -> Parser.parseDeadline("read book /by    "));
    }

    // ---------- event ----------

    @Test
    public void parseEvent_datesOnly_runsFromMidnightToTheLastMinute() throws Exception {
        Event event = Parser.parseEvent("conference /from 2019-10-15 /to 2019-10-17");
        assertEquals(LocalDateTime.of(2019, 10, 15, 0, 0), event.getFrom());
        assertEquals(LocalDateTime.of(2019, 10, 17, 23, 59), event.getTo());
    }

    @Test
    public void parseEvent_startAndEndAtTheSameMoment_accepted() throws Exception {
        Event event = Parser.parseEvent("instant /from 2019-10-15 1400 /to 2019-10-15 1400");
        assertEquals(event.getFrom(), event.getTo());
    }

    @Test
    public void parseEvent_endBeforeStart_throwsEventFormatException() {
        assertThrows(EventFormatException.class,
                () -> Parser.parseEvent("backwards /from 2019-10-15 1600 /to 2019-10-15 1400"));
    }

    @Test
    public void parseEvent_endDayBeforeStartDay_throwsEventFormatException() {
        // Both are dates alone, so the defaults decide: the 17th starts at
        // midnight and the 15th ends at 23:59, which is still backwards.
        assertThrows(EventFormatException.class,
                () -> Parser.parseEvent("backwards /from 2019-10-17 /to 2019-10-15"));
    }

    @Test
    public void parseEvent_toBeforeFrom_throwsEventFormatException() {
        assertThrows(EventFormatException.class,
                () -> Parser.parseEvent("party /to 2019-10-15 /from 2019-10-14"));
    }

    @Test
    public void parseEvent_noToPart_throwsEventFormatException() {
        assertThrows(EventFormatException.class,
                () -> Parser.parseEvent("meeting /from 2019-10-15"));
    }

    // ---------- task number ----------

    @Test
    public void parsePosition_number_returnsIt() throws Exception {
        assertEquals(3, Parser.parsePosition(" 3 "));
    }

    @Test
    public void parsePosition_zeroAndNegative_areReadAsNumbers() throws Exception {
        // Whether a task sits there is the list's question, not the parser's.
        assertEquals(0, Parser.parsePosition("0"));
        assertEquals(-1, Parser.parsePosition("-1"));
    }

    @Test
    public void parsePosition_notANumber_throwsTaskNumberFormatException() {
        assertThrows(TaskNumberFormatException.class, () -> Parser.parsePosition("abc"));
    }

    @Test
    public void parsePosition_decimal_throwsTaskNumberFormatException() {
        assertThrows(TaskNumberFormatException.class, () -> Parser.parsePosition("1.5"));
    }

    @Test
    public void parsePosition_tooBigForAnInt_throwsTaskNumberFormatException() {
        assertThrows(TaskNumberFormatException.class,
                () -> Parser.parsePosition("99999999999"));
    }

    @Test
    public void parsePosition_empty_throwsTaskNumberFormatException() {
        assertThrows(TaskNumberFormatException.class, () -> Parser.parsePosition(""));
    }
}
