// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-28, for A-JUnit. The cases come from the edge
// cases I had found by running the program by hand. I reviewed the code
// before committing it.
// ---------------------------------------------------------------------

package gudgoi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import gudgoi.exception.TaskLoadException;
import gudgoi.task.Deadline;
import gudgoi.task.Event;
import gudgoi.task.Task;
import gudgoi.task.Todo;

/**
 * Tests writing the agenda and reading it back.
 * <p>
 * Every test writes into a folder JUnit creates and deletes for it, so no test
 * can touch a real agenda or leave anything behind.
 * <p>
 * Tasks are compared by their save form rather than with {@code equals}, which
 * the task types do not define. The save form carries every field that survives
 * a restart, so two tasks with the same save form are the same task as far as
 * storage is concerned.
 */
public class StorageTest {

    /** JUnit makes this folder before each test and deletes it after. */
    @TempDir
    private Path folder;

    private Storage storageIn(String... lines) throws IOException {
        Path file = this.folder.resolve("saved.txt");
        if (lines.length > 0) {
            Files.write(file, List.of(lines));
        }
        return new Storage(file);
    }

    // ---------- writing, then reading ----------

    @Test
    public void saveThenLoad_allThreeTaskTypes_roundTripsUnchanged() throws Exception {
        Storage storage = storageIn();
        Todo todo = new Todo("read book");
        Deadline deadline = new Deadline("pay rent", LocalDateTime.of(2019, 10, 15, 18, 0));
        Event event = new Event("sync",
                LocalDateTime.of(2019, 10, 15, 9, 0),
                LocalDateTime.of(2019, 10, 15, 10, 0));
        storage.save(List.of(todo, deadline, event));

        List<Task> loaded = storage.load();
        assertEquals(3, loaded.size());
        assertEquals(todo.toSaveFormat(), loaded.get(0).toSaveFormat());
        assertEquals(deadline.toSaveFormat(), loaded.get(1).toSaveFormat());
        assertEquals(event.toSaveFormat(), loaded.get(2).toSaveFormat());
    }

    @Test
    public void saveThenLoad_doneTask_staysDone() throws Exception {
        Storage storage = storageIn();
        Todo todo = new Todo("read book");
        todo.mark();
        storage.save(List.of(todo));

        assertTrue(storage.load().get(0).isMarked());
    }

    @Test
    public void saveThenLoad_separatorInsideTheDescription_survives() throws Exception {
        // A bare | would look like a field separator on the way back in.
        Storage storage = storageIn();
        Todo todo = new Todo("pay rent | utilities");
        storage.save(List.of(todo));

        assertEquals("[T][ ] pay rent | utilities", storage.load().get(0).toString());
    }

    @Test
    public void saveThenLoad_separatorInsideADeadlineDescription_doesNotShiftTheFields()
            throws Exception {
        Storage storage = storageIn();
        Deadline deadline = new Deadline("a | b", LocalDateTime.of(2019, 10, 15, 9, 0));
        storage.save(List.of(deadline));

        Task loaded = storage.load().get(0);
        assertEquals(deadline.toSaveFormat(), loaded.toSaveFormat());
        assertEquals("[D][ ] a | b (by: Oct 15 2019, 09:00)", loaded.toString());
    }

    @Test
    public void save_emptyList_leavesAFileThatLoadsAsEmpty() throws Exception {
        Storage storage = storageIn();
        storage.save(List.of());
        assertTrue(storage.load().isEmpty());
    }

    // ---------- reading a file this program did not write ----------

    @Test
    public void load_noFileAtAll_givesAnEmptyAgenda() throws Exception {
        assertTrue(storageIn().load().isEmpty());
    }

    @Test
    public void load_blankLinesBetweenTasks_areIgnored() throws Exception {
        Storage storage = storageIn("T | 0 | first", "", "   ", "T | 1 | second");
        assertEquals(2, storage.load().size());
    }

    @Test
    public void load_lineWithTooManyFields_throwsAndDeletesTheFile() throws Exception {
        Storage storage = storageIn("T | 1 | good", "T | 1 | a | b | c");
        assertThrows(TaskLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("saved.txt")));
    }

    @Test
    public void load_doneFlagThatIsNotZeroOrOne_throwsAndDeletesTheFile() throws Exception {
        Storage storage = storageIn("T | 2 | odd flag");
        assertThrows(TaskLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("saved.txt")));
    }

    @Test
    public void load_timeInTheFormatUsedBeforeLevel8_throwsAndDeletesTheFile() throws Exception {
        // A file written when times were free text can no longer be read.
        Storage storage = storageIn("D | 0 | return book | June 6th");
        assertThrows(TaskLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("saved.txt")));
    }

    @Test
    public void load_unknownTypeLetter_throwsAndDeletesTheFile() throws Exception {
        Storage storage = storageIn("X | 0 | what is this");
        assertThrows(TaskLoadException.class, storage::load);
        assertFalse(Files.exists(this.folder.resolve("saved.txt")));
    }

    @Test
    public void load_damagedLineAfterGoodOnes_keepsNothing() throws Exception {
        // Part of an agenda is worse than none, because the user cannot see
        // what is missing.
        Storage storage = storageIn("T | 0 | first", "T | 0 | second", "rubbish");
        assertThrows(TaskLoadException.class, storage::load);
    }

    @Test
    public void save_folderDoesNotExistYet_createsIt() throws Exception {
        Path nested = this.folder.resolve("data").resolve("saved.txt");
        new Storage(nested).save(List.of(new Todo("read book")));
        assertTrue(Files.exists(nested));
    }
}
