// ---------------------------------------------------------------------
// AI-ASSISTED CODE — CITATION
// This entire class was generated by Claude (Anthropic), used through
// Claude Code, on 2026-08-28, for A-JUnit. I reviewed the code before
// committing it.
// ---------------------------------------------------------------------

package gudgoi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.junit.jupiter.api.Test;

import gudgoi.exception.OutOfBoundException;
import gudgoi.task.Task;
import gudgoi.task.Todo;

/**
 * Tests the agenda.
 * <p>
 * This class is the only one that knows the user counts from 1 while a list
 * indexes from 0, so the tests concentrate on the two ends of that range, where
 * an error of one would hide.
 */
public class TaskListTest {

    private TaskList listOf(String... descriptions) {
        TaskList tasks = new TaskList();
        for (String d : descriptions) {
            tasks.add(new Todo(d));
        }
        return tasks;
    }

    // ---------- positions ----------

    @Test
    public void get_firstPosition_returnsTheFirstTask() throws Exception {
        assertEquals("[T][ ] a", listOf("a", "b", "c").get(1).toString());
    }

    @Test
    public void get_lastPosition_returnsTheLastTask() throws Exception {
        assertEquals("[T][ ] c", listOf("a", "b", "c").get(3).toString());
    }

    @Test
    public void get_zero_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> listOf("a").get(0));
    }

    @Test
    public void get_onePastTheEnd_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> listOf("a", "b").get(3));
    }

    @Test
    public void get_negativePosition_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> listOf("a").get(-1));
    }

    @Test
    public void get_anyPositionWhenEmpty_throwsOutOfBoundException() {
        assertThrows(OutOfBoundException.class, () -> new TaskList().get(1));
    }

    // ---------- changing the list ----------

    @Test
    public void remove_middlePosition_returnsItAndClosesTheGap() throws Exception {
        TaskList tasks = listOf("a", "b", "c");
        assertEquals("[T][ ] b", tasks.remove(2).toString());
        assertEquals(2, tasks.size());
        assertEquals("[T][ ] c", tasks.get(2).toString());
    }

    @Test
    public void remove_thenGetTheOldLastPosition_throwsOutOfBoundException() throws Exception {
        TaskList tasks = listOf("a", "b", "c");
        tasks.remove(1);
        assertThrows(OutOfBoundException.class, () -> tasks.get(3));
    }

    @Test
    public void insert_afterRemovingTheSamePosition_putsTheListBack() throws Exception {
        // This is the undo a failed save relies on.
        TaskList tasks = listOf("a", "b", "c");
        Task taken = tasks.remove(2);
        tasks.insert(2, taken);

        assertEquals(3, tasks.size());
        assertEquals("[T][ ] b", tasks.get(2).toString());
    }

    @Test
    public void removeLast_afterAdding_undoesTheAdd() throws Exception {
        TaskList tasks = listOf("a", "b");
        tasks.add(new Todo("c"));
        tasks.removeLast();

        assertEquals(2, tasks.size());
        assertEquals("[T][ ] b", tasks.get(2).toString());
    }

    @Test
    public void removeLast_onAnEmptyList_doesNothing() {
        TaskList tasks = new TaskList();
        tasks.removeLast();
        assertTrue(tasks.isEmpty());
    }

    // ---------- what it hands out ----------

    @Test
    public void constructor_fromAList_copiesIt() throws Exception {
        // A later change to the caller's list must not reach the agenda.
        List<Task> given = new java.util.ArrayList<>(List.of(new Todo("a")));
        TaskList tasks = new TaskList(given);
        given.add(new Todo("b"));

        assertEquals(1, tasks.size());
    }

    @Test
    public void asList_theViewItReturns_cannotBeChanged() {
        List<Task> view = listOf("a").asList();
        assertThrows(UnsupportedOperationException.class, () -> view.add(new Todo("b")));
    }
}
